BEGIN READ ONLY; SET LOCAL statement_timeout='20s'; SET LOCAL lock_timeout='2s';
SELECT jsonb_build_object('at',clock_timestamp(),'database',current_database(),'role',current_user,'backend_pid',pg_backend_pid(),'baseline',(select jsonb_agg(t) from (
select 'public function body/signature/owner/ACL' as check_name, md5((select jsonb_agg(jsonb_build_object('name',p.proname,'args',pg_get_function_identity_arguments(p.oid),'md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl) order by p.proname,pg_get_function_identity_arguments(p.oid)) from pg_proc p where p.pronamespace='public'::regnamespace and p.prokind='f')::text) is not distinct from 'c0dd840db9d54c8b4f641accec3168a2' as matches
union all
select 'migration history' as check_name, md5((select jsonb_agg(t order by version) from (select version,name from supabase_migrations.schema_migrations)t)::text) is not distinct from '304f86a3786d03a956107a98febaf20d' as matches
union all
select 'Cron jobs' as check_name, md5((select jsonb_agg(t order by jobid) from (select jobid,jobname,schedule,command,active,database,username from cron.job)t)::text) is not distinct from '23ecae21c408e484c8abcb81229d7fa4' as matches
union all
select 'columns' as check_name, md5((select jsonb_agg(jsonb_build_object('table',c.relname,'column',a.attname,'type',format_type(a.atttypid,a.atttypmod),'not_null',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid),'identity',a.attidentity,'generated',a.attgenerated) order by c.relname,a.attnum) from pg_class c join pg_attribute a on a.attrelid=c.oid left join pg_attrdef d on d.adrelid=c.oid and d.adnum=a.attnum where c.relnamespace='public'::regnamespace and c.relkind in ('r','p','v','m') and a.attnum>0 and not a.attisdropped)::text) is not distinct from 'ff302978bb0cb375dc5afb503eae9798' as matches
union all
select 'constraints' as check_name, md5((select jsonb_agg(jsonb_build_object('table',c.conrelid::regclass::text,'name',c.conname,'definition',pg_get_constraintdef(c.oid),'validated',c.convalidated) order by c.conrelid::regclass::text,c.conname) from pg_constraint c where c.connamespace='public'::regnamespace)::text) is not distinct from '3f422037e810338f7cf9adbc47ffe578' as matches
union all
select 'triggers' as check_name, md5((select jsonb_agg(jsonb_build_object('table',t.tgrelid::regclass::text,'name',t.tgname,'definition',pg_get_triggerdef(t.oid),'enabled',t.tgenabled,'function',t.tgfoid::regprocedure::text) order by t.tgrelid::regclass::text,t.tgname) from pg_trigger t where not t.tgisinternal and t.tgrelid in (select oid from pg_class where relnamespace in ('public'::regnamespace,'auth'::regnamespace)))::text) is not distinct from '1e9d5e31d31948d24cc75f7052abc452' as matches
union all
select 'table RLS and grants' as check_name, md5((select jsonb_object_agg(relname,jsonb_build_object('name',relname,'kind',relkind,'rls',relrowsecurity,'force_rls',relforcerowsecurity,'acl',relacl)) from pg_class where relnamespace='public'::regnamespace and relkind in ('r','p','v','m'))::text) is not distinct from '7b0c3845ba3966b5261a479a6a4bb95e' as matches
union all
select 'indexes' as check_name, md5((select jsonb_object_agg(indexname,to_jsonb(t)) from (select tablename,indexname,indexdef from pg_indexes where schemaname='public')t)::text) is not distinct from '0a6ab21d8af915f1c0d39041d57d05f5' as matches
union all
select 'policies' as check_name, md5((select jsonb_object_agg(schemaname||'.'||tablename||'.'||policyname,to_jsonb(t)) from (select * from pg_policies where schemaname='public')t)::text) is not distinct from 'de49453e0afda5128cb753ba7cc875c5' as matches
)t),'rows',jsonb_build_object('users',(select jsonb_build_object('count',count(*),'md5',md5(coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text)::text,'[]'))) from public.users t),'guilds',(select jsonb_build_object('count',count(*),'md5',md5(coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text)::text,'[]'))) from public.guilds t),'guild_members',(select jsonb_build_object('count',count(*),'md5',md5(coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text)::text,'[]'))) from public.guild_members t),'raid_bosses',(select jsonb_build_object('count',count(*),'md5',md5(coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text)::text,'[]'))) from public.raid_bosses t),'battle_replay_sessions',(select jsonb_build_object('count',count(*),'md5',md5(coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text)::text,'[]'))) from public.battle_replay_sessions t),'battle_replay_events',(select jsonb_build_object('count',count(*),'md5',md5(coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text)::text,'[]'))) from public.battle_replay_events t),'raid_damage_logs',(select jsonb_build_object('count',count(*),'md5',md5(coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text)::text,'[]'))) from public.raid_damage_logs t),'raid_instance_user_progress',(select jsonb_build_object('count',count(*),'md5',md5(coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text)::text,'[]'))) from public.raid_instance_user_progress t),'presents',(select jsonb_build_object('count',count(*),'md5',md5(coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text)::text,'[]'))) from public.presents t),'ranking_reward_notifications',(select jsonb_build_object('count',count(*),'md5',md5(coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text)::text,'[]'))) from public.ranking_reward_notifications t),'kpi_overview_saved_results',(select jsonb_build_object('count',count(*),'md5',md5(coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text)::text,'[]'))) from public.kpi_overview_saved_results t),'kpi_aggregation_runs',(select jsonb_build_object('count',count(*),'md5',md5(coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text)::text,'[]'))) from public.kpi_aggregation_runs t),'kpi_metric_snapshots',(select jsonb_build_object('count',count(*),'md5',md5(coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text)::text,'[]'))) from public.kpi_metric_snapshots t)),
'room_relation',to_regclass('public.raid_rooms'),'legacy_setting_relation',to_regclass('public.raid_legacy_settings'),
'cron_jobs',(select jsonb_agg(t order by jobid) from (select jobid,jobname,schedule,command,active from cron.job)t),
'cron_running',(select coalesce(jsonb_agg(t),'[]') from (select jobid,runid,status,start_time,end_time from cron.job_run_details where status in ('starting','running','connecting','sending') and end_time is null)t),
'other_active_sessions',(select coalesce(jsonb_agg(t),'[]') from (select pid,usename,application_name,backend_type,state,xact_start,query_start,wait_event_type,wait_event from pg_stat_activity where datname=current_database() and pid<>pg_backend_pid() and state is distinct from 'idle' and backend_type='client backend')t)
) as audit; ROLLBACK;
