import fs from 'node:fs';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
process.on('uncaughtException',e=>{console.error(e.message,e.code||'',e.where||'');process.exit(1);});
const {PGlite}=await import(pathToFileURL(process.env.PGLITE_RUNTIME));
const db=new PGlite();
const sql=name=>fs.readFileSync('supabase/migrations/'+name,'utf8');
const fn=(source,name)=>{const start=source.search(new RegExp('create (?:or replace )?function public\\.'+name+'\\(','i'));assert.ok(start>=0);const s=source.slice(start),tag=s.match(/as\s+(\$\w*\$)/i)[1];return s.slice(0,s.indexOf(tag,s.indexOf(tag)+tag.length)+tag.length)+';';};
await db.exec(`
create role anon;create role authenticated;create role service_role;create schema auth;create schema cron;
create function auth.uid() returns uuid language sql as $$select '00000000-0000-0000-0000-000000000001'::uuid$$;
create table mission_events(id text primary key,display_name text,start_at timestamptz,progress_end_at timestamptz,claim_deadline timestamptz,banner_image_url text,banner_title text,banner_subtitle text,banner_cta_label text,is_enabled boolean,updated_at timestamptz);
create table missions(id text primary key,event_id text,trigger_type text,target_value int,is_enabled boolean);
create table user_missions(user_id uuid,mission_id text,status text,current_progress int,progress_val int,updated_at timestamptz);
insert into mission_events(id,display_name,start_at,progress_end_at,is_enabled) values('GVG_PREP_20260904','準備',now()-interval '10 days',now()+interval '1 day',true);
insert into missions values('one','GVG_PREP_20260904','NORMAL',1,true),('complete','GVG_PREP_20260904','GVG_PREP_REQUIRED_MISSIONS_COMPLETED',1,true);
insert into user_missions values(auth.uid(),'one','CLEAR',1,1,now()),(auth.uid(),'complete','PROGRESS',0,0,now());
create table ranking_seasons(id uuid primary key,ranking_type text,status text,starts_at timestamptz,ends_at timestamptz,updated_at timestamptz);
create table ranking_guild_power_season_master(season_id uuid,event_key text);
create table guilds(id uuid primary key,name text);
create table guild_members(guild_id uuid,user_id uuid);
create table power_fixture(user_id uuid,power bigint);
create function calculate_user_total_power(uuid) returns bigint language sql as $$select power from power_fixture where user_id=$1$$;
create table ranking_guild_exclusions(guild_id uuid);
create table cosmetic_master(id text primary key,owner_scope text,slot text,active boolean,metadata jsonb);
create table ranking_guild_power_season_snapshots(season_id uuid,guild_id uuid,guild_name text,total_power bigint,member_count int,rank_position int,primary key(season_id,guild_id));
create table ranking_guild_power_reward_grants(season_id uuid,guild_id uuid,cosmetic_id text,rank_position int,primary key(season_id,guild_id,cosmetic_id));
create table guild_cosmetics(guild_id uuid,cosmetic_id text,source_type text,source_reference text,primary key(guild_id,cosmetic_id));
create table ranking_guild_power_reward_recipients(season_id uuid,guild_id uuid,recipient_user_id uuid,primary key(season_id,guild_id,recipient_user_id));
create table ranking_reward_notifications(recipient_user_id uuid,period_kind text,period_key text,awarded_at timestamptz,acknowledged_at timestamptz,unique(recipient_user_id,period_kind,period_key));
create table ranking_guild_power_finalization_audits(season_id uuid primary key,ranked_guild_count int,reward_grant_count int);
create table cron.job(jobid bigint,jobname text);
create function cron.unschedule(bigint) returns boolean language sql as $$select true$$;
create function activate_preopen_guild_power_season() returns jsonb language sql as $$select '{}'::jsonb$$;
insert into ranking_seasons values('00000000-0000-0000-0000-000000000010','GUILD_POWER','ACTIVE',now()-interval '10 days',now()-interval '1 hour',now());
insert into ranking_guild_power_season_master values('00000000-0000-0000-0000-000000000010','PREOPEN_GUILD_POWER_2026');
insert into guilds select ('00000000-0000-0000-0000-00000000000'||n)::uuid,'Guild '||n from generate_series(1,3)n;
insert into guild_members select id,id from guilds;
insert into power_fixture select id,case name when 'Guild 1' then 100 when 'Guild 2' then 90 else 80 end from guilds;
insert into cosmetic_master values('limited_fixture','GUILD','GUILD_EMBLEM',true,'{}'),('standard_fixture','GUILD','GUILD_EMBLEM',true,'{"standard":true}');
`);
await db.exec(fn(sql('20260912153009_mission_claim_deadline_and_event_history.sql'),'get_active_mission_events'));
await db.exec(fn(sql('20260903000235_preopen_gvg_preparation_missions.sql'),'refresh_special_event_completion'));
await db.exec(sql('20260914112059_formal_open_season_claim_contract.sql'));
const scalar=async q=>(await db.query(q)).rows[0].v;
assert.equal((await scalar('select get_active_mission_events() v')).length,1,'null deadline remains visible');
await assert.rejects(db.exec("select close_gvg_preparation_missions_v1(null,now())"),/timestamps required/);
await assert.rejects(db.exec("select close_gvg_preparation_missions_v1(now(),now()+interval '1 hour')"),/timestamps required/);
await db.exec("select close_gvg_preparation_missions_v1(now()-interval '1 minute',now())");
await db.exec("select close_gvg_preparation_missions_v1(progress_end_at,claim_deadline-interval '30 days') from mission_events");
await assert.rejects(db.exec("select close_gvg_preparation_missions_v1(progress_end_at,claim_deadline-interval '31 days') from mission_events"));
assert.equal(await scalar("select extract(epoch from (claim_deadline-now()))::int v from mission_events"),30*86400);
assert.equal((await scalar('select get_active_mission_events() v')).length,1);
await db.exec("select refresh_special_event_completion(auth.uid(),'GVG_PREP_20260904')");
assert.equal(await scalar("select status v from user_missions where mission_id='complete'"),'PROGRESS','post-close claims must not advance completion mission');
await db.exec("update user_missions set status='CLAIMED' where mission_id='one'");
assert.equal((await scalar('select get_active_mission_events() v')).length,1,'CLAIMED history visible within claim window');
await db.exec("update user_missions set status='PROGRESS'");
assert.equal((await scalar('select get_active_mission_events() v')).length,0,'closed event with no achievement hidden');
await db.exec("update user_missions set status='CLEAR' where mission_id='one'");
await db.exec("update mission_events set claim_deadline=clock_timestamp()");
assert.equal((await scalar('select get_active_mission_events() v')).length,0,'expired events hidden with CLEAR rows retained');
assert.equal(await scalar("select count(*)::int v from user_missions where status='CLEAR'"),1);
await assert.rejects(db.exec("select finalize_preopen_guild_power_season_v2('missing')"),/NOT CONFIGURED/);
await assert.rejects(db.exec("select finalize_preopen_guild_power_season_v2('standard_fixture')"),/NOT CONFIGURED/);
assert.equal(await scalar('select count(*)::int v from ranking_guild_power_season_snapshots'),0);
await db.exec("update ranking_seasons set status='CLOSED'");
await assert.rejects(db.exec("select finalize_preopen_guild_power_season_v2('limited_fixture')"),/Closed season without/);
assert.equal(await scalar('select count(*)::int v from ranking_guild_power_season_snapshots'),0);
await db.exec("update ranking_seasons set status='ACTIVE'");
const result=await scalar("select finalize_preopen_guild_power_season_v2('limited_fixture') v");assert.equal(result.status,'FINALIZED');assert.equal(result.reward_grant_count,1);assert.equal(result.ranked_guild_count,3);
assert.equal(await scalar('select count(*)::int v from ranking_guild_power_reward_recipients'),3,'all members snapshotted');
assert.equal(await scalar('select count(*)::int v from ranking_reward_notifications'),1,'winner notification only');
assert.equal(await scalar('select rank_position v from ranking_guild_power_reward_grants'),1);
await db.exec('update ranking_reward_notifications set acknowledged_at=now()');
assert.equal((await scalar("select finalize_preopen_guild_power_season_v2('limited_fixture') v")).status,'ALREADY_FINALIZED');
assert.equal(await scalar('select count(*)::int v from guild_cosmetics'),1);
assert.equal(await scalar('select count(*)::int v from ranking_reward_notifications where acknowledged_at is null'),0);
assert.equal(await scalar("select has_function_privilege('authenticated','finalize_preopen_guild_power_season_v2(text)','EXECUTE') v"),false);
await db.close();console.log('PASS: 30-day close contract, expired event hidden without losing CLEAR, stopped completion progress, first-only Guild reward, full member snapshot, exactly-once grants/notifications, invalid/standard emblem rejected. No production cutover executed.');
