process.on('uncaughtException',e=>{console.error(e.message, e.code || '', e.where || '');process.exit(1);});
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const runtime=process.env.PGLITE_RUNTIME;
if(!runtime)throw new Error('Set PGLITE_RUNTIME to the isolated @electric-sql/pglite dist/index.js');
const {PGlite}=await import(pathToFileURL(runtime));
const db=new PGlite();
// Contract fixture: existing Raid registration/power/daily services are explicit doubles.
// This tests new SQL execution and idempotency, not live Raid authority integration.
await db.exec(`
create role anon;create role authenticated;create role service_role;create schema auth;create schema private;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
create table users(id uuid primary key,level int,power bigint);
create table tutorial_progress(user_id uuid,step_id text);
create table user_patrols(id uuid primary key,user_id uuid,status text,battle_result text,battle_resolved boolean,has_battle_event boolean,course_id text,quest_id text);
create table canonical_quest_master(version text,quest_id text,town_id text,is_production_enabled boolean);
create table canonical_raid_variants(raid_variant_id text primary key,area_id text,raid_name text,max_hp bigint,member_character_ids jsonb,is_production_enabled boolean);
create table raid_room_creation_settings(singleton boolean,enabled boolean);
create table raid_room_lifecycle_rules(difficulty text,max_active_rooms int,duration_hours int);
create table raid_bosses(id uuid primary key,boss_id text,boss_master_id text,current_hp bigint,max_hp bigint,base_id text,status text,spawned_at timestamptz,expires_at timestamptz,cycle_id uuid,rotation_date date,raid_variant_id text,raid_day_key text,outcome_finalized_at timestamptz);
create table raid_rooms(id uuid primary key,raid_boss_instance_id uuid,owner_user_id uuid,difficulty_id text);
create table raid_room_clear_rewards(room_id uuid,user_id uuid);
create table raid_room_rescue_rewards(room_id uuid,user_id uuid);
create table presents(user_id uuid,item_id text,quantity int,message text,status text,created_at timestamptz,expire_at timestamptz,source_kind text,source_key text,source_metadata jsonb);
create function quest_town_key(v text) returns text language sql immutable as $$select lower(v)$$;
create function calculate_user_total_power(u uuid) returns bigint language sql stable as $$select power from public.users where id=u$$;
create function _raid_room_power_gate_v1(d text,p bigint) returns jsonb language sql stable as $$select jsonb_build_object('status',case when d='beginner' or p>=200000 then 'passed' else 'failed' end)$$;
create function private.raid_daily_targets_v1() returns jsonb language sql stable as $$select '{"targets":[{"variantId":"SHIBUYA"}]}'::jsonb$$;
create function _raid_room_register_v1(i uuid,u uuid,d text) returns jsonb language plpgsql as $$declare r uuid:=gen_random_uuid();begin insert into public.raid_rooms values(r,i,u,d);return jsonb_build_object('roomId',r);end$$;
insert into users values('00000000-0000-0000-0000-000000000001',5,300000),('00000000-0000-0000-0000-000000000002',5,300000);
insert into tutorial_progress select id,'COMPLETE' from users;
insert into canonical_quest_master values('2026-08-30','Q_EASY','shibuya',true);
insert into canonical_raid_variants values('SHIBUYA','SHIBUYA','強敵',1000,'["char_ageha_01"]',true);
insert into raid_room_creation_settings values(true,true);
insert into raid_room_lifecycle_rules values('beginner',10,24),('intermediate',10,24),('advanced',10,24);
select set_config('test.uid','00000000-0000-0000-0000-000000000001',false);
`);
await db.exec(fs.readFileSync('supabase/migrations/20260913105642_quest_raid_encounter.sql','utf8'));
const scalar=async sql=>(await db.query(sql)).rows[0].v;
async function quest(n,user=1,result='VICTORY'){
 const id=`00000000-0000-0000-0001-${String(n).padStart(12,'0')}`;
 await db.query(`insert into user_patrols values($1,$2,'CLAIMABLE',$3,true,true,'Q_EASY',null)`,[id,`00000000-0000-0000-0000-${String(user).padStart(12,'0')}`,result]);
 await db.query(`update user_patrols set status='COMPLETED' where id=$1`,[id]);return id;
}
const resolve=async id=>(await db.query('select resolve_quest_raid_encounter_v1($1) v',[id])).rows[0].v;
assert.equal((await resolve(await quest(1))).status,'NO_ENCOUNTER','disabled does not backfill');
await db.exec(`update quest_raid_encounter_settings set enabled=true,probability_bp=0,guaranteed_after=2,personal_active_limit=5,beginner_weight=0,intermediate_weight=0,advanced_weight=1;insert into quest_raid_encounter_bonus_items values('advanced','growth_large',2)`);
assert.equal((await resolve(await quest(2,1,'DEFEAT'))).status,'NO_ENCOUNTER');
const id=await quest(3);const first=await resolve(id);
assert.equal(first.status,'CREATED');assert.equal(first.difficulty,'advanced','Easy Quest can create advanced Raid');
assert.equal((await resolve(id)).roomId,first.roomId,'same Quest reuses Room');
assert.equal(await scalar('select count(*)::int v from raid_rooms'),1);
const foreign=await quest(4,2);assert.equal((await resolve(foreign)).status,'NO_ENCOUNTER','no access to other owner');
assert.equal((await resolve(await quest(5))).status,'NO_ENCOUNTER','zero chance miss recorded');
assert.equal((await resolve(await quest(6))).status,'CREATED','guarantee after miss');
await db.exec('update quest_raid_encounter_bonus_items set quantity=99');
await db.query(`insert into raid_room_clear_rewards values($1,'00000000-0000-0000-0000-000000000001');`,[first.roomId]);
await db.query(`insert into raid_room_rescue_rewards values($1,'00000000-0000-0000-0000-000000000001');`,[first.roomId]);
assert.equal(await scalar('select count(*)::int v from presents'),1,'Clear+Rescue bonus once');
assert.equal(await scalar('select quantity v from presents limit 1'),2,'creation reward snapshot preserved');
await db.query(`insert into raid_room_rescue_rewards values($1,'00000000-0000-0000-0000-000000000002');`,[first.roomId]);
assert.equal(await scalar('select count(*)::int v from presents'),2,'rescuers get same bonus');
assert.equal((await db.query('select acknowledge_quest_raid_encounter_v1($1) v',[id])).rows[0].v,true);
assert.equal((await db.query('select acknowledge_quest_raid_encounter_v1($1) v',[id])).rows[0].v,true,'ack idempotent');
const list=await scalar('select get_quest_raid_encounters_v1() v');assert.equal(list.find(e=>e.patrolId===id).acknowledged,true);
await db.exec('update raid_room_lifecycle_rules set max_active_rooms=1');
const cap=await resolve(await quest(7));assert.equal(cap.status,'DEFERRED');
assert.equal(await scalar('select count(*)::int v from raid_rooms'),2);
assert.equal(await scalar(`select has_function_privilege('anon','resolve_quest_raid_encounter_v1(uuid)','EXECUTE') v`),false);
await db.exec(`update raid_room_lifecycle_rules set max_active_rooms=10;update quest_raid_encounter_settings set probability_bp=10000;
create or replace function _raid_room_register_v1(i uuid,u uuid,d text) returns jsonb language plpgsql as $$begin raise exception 'simulated transient registration failure';end$$;`);
const retryId=await quest(8);assert.equal((await resolve(retryId)).status,'DEFERRED');
assert.equal(await scalar(`select status v from quest_raid_encounters where patrol_id='${retryId}'`),'DRAWN','draw persists if registration fails');
assert.equal(await scalar('select count(*)::int v from raid_bosses'),2,'failed creation rolls back boss');
await db.exec(`update quest_raid_encounter_settings set advanced_weight=0,beginner_weight=1;
create or replace function _raid_room_register_v1(i uuid,u uuid,d text) returns jsonb language plpgsql as $$declare r uuid:=gen_random_uuid();begin insert into public.raid_rooms values(r,i,u,d);return jsonb_build_object('roomId',r);end$$;`);
assert.equal((await resolve(retryId)).difficulty,'advanced','retry does not change drawn difficulty');
await db.exec(`select set_config('test.uid','00000000-0000-0000-0000-000000000002',false)`);
assert.equal((await db.query('select acknowledge_quest_raid_encounter_v1($1) v',[id])).rows[0].v,false);
await db.close();console.log('PASS: Encounter SQL, disabled/no backfill, victory, first/guarantee, grade independence, owner isolation, cap, replay, snapshot, Clear+Rescue dedup, acknowledgement, grants. Raid dependencies are contract doubles.');
