process.on('uncaughtException',e=>{console.error(e.message, e.code || '', e.where || '');process.exit(1);});
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const runtime=process.env.PGLITE_RUNTIME;
if(!runtime)throw new Error('Set PGLITE_RUNTIME to the isolated @electric-sql/pglite dist/index.js');
const {PGlite}=await import(pathToFileURL(runtime));
const db=new PGlite();
// Contract fixture: existing Raid registration/power/daily services are explicit doubles.
// This tests new SQL execution and idempotency, not live Raid authority integration.
await db.exec(`
create role anon;create role authenticated;create role service_role;create schema auth;create schema private;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
create table users(id uuid primary key,level int,power bigint);
create table tutorial_progress(user_id uuid,step_id text);
create table user_patrols(id uuid primary key,user_id uuid,status text,battle_result text,battle_resolved boolean,has_battle_event boolean,course_id text,quest_id text);
create table canonical_quest_master(version text,quest_id text,town_id text,is_production_enabled boolean);
create table canonical_raid_variants(raid_variant_id text primary key,area_id text,raid_name text,max_hp bigint,member_character_ids jsonb,is_production_enabled boolean);
create table raid_room_creation_settings(singleton boolean,enabled boolean);
create table raid_room_lifecycle_rules(difficulty text,max_active_rooms int,duration_hours int);
create table raid_bosses(id uuid primary key,boss_id text,boss_master_id text,current_hp bigint,max_hp bigint,base_id text,status text,spawned_at timestamptz,expires_at timestamptz,cycle_id uuid,rotation_date date,raid_variant_id text,raid_day_key text,outcome_finalized_at timestamptz);
create table raid_rooms(id uuid primary key,raid_boss_instance_id uuid,owner_user_id uuid,difficulty_id text);
create table raid_room_clear_rewards(room_id uuid,user_id uuid);
create table raid_room_rescue_rewards(room_id uuid,user_id uuid);
create table presents(user_id uuid,item_id text,quantity int,message text,status text,created_at timestamptz,expire_at timestamptz,source_kind text,source_key text,source_metadata jsonb);
create function quest_town_key(v text) returns text language sql immutable as $$select lower(v)$$;
create function calculate_user_total_power(u uuid) returns bigint language sql stable as $$select power from public.users where id=u$$;
create function _raid_room_power_gate_v1(d text,p bigint) returns jsonb language sql stable as $$select jsonb_build_object('status',case when d='beginner' or p>=200000 then 'passed' else 'failed' end)$$;
create function private.raid_daily_targets_v1() returns jsonb language sql stable as $$select '{"targets":[{"variantId":"SHIBUYA"}]}'::jsonb$$;
create function _raid_room_register_v1(i uuid,u uuid,d text) returns jsonb language plpgsql as $$declare r uuid:=gen_random_uuid();begin insert into public.raid_rooms values(r,i,u,d);return jsonb_build_object('roomId',r);end$$;
insert into users values('00000000-0000-0000-0000-000000000001',5,300000),('00000000-0000-0000-0000-000000000002',5,300000);
insert into tutorial_progress select id,'COMPLETE' from users;
insert into canonical_quest_master values('2026-08-30','Q_EASY','shibuya',true);
insert into canonical_raid_variants values('SHIBUYA','SHIBUYA','強敵',1000,'["char_ageha_01"]',true);
insert into raid_room_creation_settings values(true,true);
insert into raid_room_lifecycle_rules values('beginner',10,24),('intermediate',10,24),('advanced',10,24);
select set_config('test.uid','00000000-0000-0000-0000-000000000001',false);
`);
await db.exec(fs.readFileSync('supabase/migrations/20260913105642_quest_raid_encounter.sql','utf8'));
const scalar=async sql=>(await db.query(sql)).rows[0].v;
async function quest(n,user=1,result='VICTORY'){
 const id=`00000000-0000-0000-0001-${String(n).padStart(12,'0')}`;
 await db.query(`insert into user_patrols values($1,$2,'CLAIMABLE',$3,true,true,'Q_EASY',null)`,[id,`00000000-0000-0000-0000-${String(user).padStart(12,'0')}`,result]);
 await db.query(`update user_patrols set status='COMPLETED' where id=$1`,[id]);return id;
}
const resolve=async id=>(await db.query('select resolve_quest_raid_encounter_v1($1) v',[id])).rows[0].v;
await db.exec(`
alter table raid_bosses add column outcome text;
alter table presents add column id uuid default gen_random_uuid() unique;
create table raid_room_members(room_id uuid,user_id uuid);
create table raid_room_rescue_members(room_id uuid,user_id uuid);
create table raid_room_difficulty_rules(difficulty text);
create table raid_room_clear_reward_rules(difficulty text,enabled boolean,minimum_contribution_damage bigint,rule_version bigint);
create table raid_room_rescue_reward_rules(difficulty text,enabled boolean,rule_version bigint,reward_version bigint);
create table raid_room_clear_reward_items(difficulty text,item_id text,quantity int);
create table raid_room_rescue_reward_items(difficulty text,item_id text,quantity int);
alter table raid_room_clear_rewards add column rule_version bigint,add column finalized_battles bigint,add column contribution_damage bigint,add column clear_gate jsonb,add column issued_at timestamptz,add column expires_at timestamptz,add unique(room_id,user_id);
alter table raid_room_rescue_rewards add column rule_version bigint,add column reward_version bigint,add column finalized_battles bigint,add column contribution_damage bigint,add column rescue_gate jsonb,add column issued_at timestamptz,add column expires_at timestamptz,add unique(room_id,user_id);
create table raid_room_clear_reward_grants(room_id uuid,user_id uuid,item_id text,quantity int,present_id uuid,primary key(room_id,user_id,item_id));
create table raid_room_rescue_reward_grants(like raid_room_clear_reward_grants including all);
create function _raid_room_clear_reward_progress_v1(r uuid,u uuid) returns jsonb language sql as $$select '{"finalizedBattles":1,"contributionDamage":100,"clearGate":{"status":"succeeded","ruleVersion":1}}'::jsonb$$;
create function _raid_room_rescue_reward_progress_v1(r uuid,u uuid) returns jsonb language sql as $$select '{"finalizedBattles":1,"contributionDamage":100,"rescueGate":{"status":"succeeded","ruleVersion":1}}'::jsonb$$;
insert into raid_room_clear_reward_rules values('advanced',true,1,1);
insert into raid_room_rescue_reward_rules values('advanced',true,1,1);
insert into raid_room_clear_reward_items values('advanced','CASH',300),('advanced','CHAR_EXP_L',2);
insert into raid_room_rescue_reward_items values('advanced','CASH',100),('advanced','EQUIP_EXP_L',3);
`);
await db.exec(fs.readFileSync('supabase/migrations/20260913120930_quest_raid_approved_occurrence_and_double_rewards.sql','utf8'));
assert.equal(await scalar('select enabled v from quest_raid_encounter_settings'),false);
assert.equal(await scalar('select probability_bp v from quest_raid_encounter_settings'),1000);
assert.equal(await scalar('select guaranteed_after v from quest_raid_encounter_settings'),11);
await db.exec('update quest_raid_encounter_settings set enabled=true,probability_bp=0,beginner_weight=0,intermediate_weight=0,advanced_weight=1');
for(let n=1;n<=10;n++) assert.equal((await resolve(await quest(n))).status,'NO_ENCOUNTER',`miss ${n}, including first has no guarantee`);
const first=await resolve(await quest(11));assert.equal(first.status,'CREATED');assert.equal(first.rewardMultiplier,2);
assert.equal(first.difficulty,'advanced');assert.equal(await scalar('select misses v from quest_raid_encounter_progress'),0);
assert.equal((await resolve(first.patrolId)).roomId,first.roomId);
assert.equal((await resolve(await quest(12))).status,'DEFERRED','personal cap');
assert.equal(await scalar('select misses v from quest_raid_encounter_progress'),0,'cap does not consume guarantee');
await db.query("update raid_bosses set outcome='DEFEAT_SUCCESS',status='DEFEATED' where id=(select raid_boss_instance_id from raid_rooms where id=$1)",[first.roomId]);
await db.query('insert into raid_room_members select $1,id from users',[first.roomId]);
await db.exec('insert into raid_room_rescue_members select * from raid_room_members');
await db.exec(`create function test_present_failure() returns trigger language plpgsql as $$begin raise exception 'test delivery failure';end$$;create trigger test_delivery before insert on presents for each row execute function test_present_failure();`);
await assert.rejects(db.query('select _issue_raid_room_clear_rewards_v1($1)',[first.roomId]),/test delivery failure/);
assert.equal(await scalar('select count(*)::int v from raid_room_clear_rewards'),0,'delivery failure rolls receipt back');
assert.equal(await scalar('select count(*)::int v from presents'),0);
await db.exec('drop trigger test_delivery on presents');
for(const kind of ['clear','rescue']) {
 assert.equal((await db.query(`select _issue_raid_room_${kind}_rewards_v1($1) v`,[first.roomId])).rows[0].v,2);
 assert.equal((await db.query(`select _issue_raid_room_${kind}_rewards_v1($1) v`,[first.roomId])).rows[0].v,0);
}
assert.equal(await scalar("select sum(quantity)::int v from presents where item_id='CASH'"),1600,'Clear and Rescue both doubled for both users');
assert.equal(await scalar("select quantity v from raid_room_clear_reward_grants where item_id='CHAR_EXP_L' limit 1"),4);
assert.equal(await scalar("select quantity v from raid_room_rescue_reward_grants where item_id='EQUIP_EXP_L' limit 1"),6);
assert.equal(await scalar('select count(*)::int v from quest_raid_encounter_bonus_grants'),0,'no obsolete fixed bonus');
assert.equal(await scalar('select count(*)::int v from presents'),8);
const manual=await scalar(`select (_raid_room_register_v1((select raid_boss_instance_id from raid_rooms limit 1),'00000000-0000-0000-0000-000000000001','advanced')->>'roomId') v`);
await db.query("insert into raid_room_members values($1,'00000000-0000-0000-0000-000000000001')",[manual]);
await db.query('select _issue_raid_room_clear_rewards_v1($1)',[manual]);
assert.equal((await db.query("select quantity v from raid_room_clear_reward_grants where room_id=$1 and item_id='CASH'",[manual])).rows[0].v,300);
assert.equal(await scalar(`select has_function_privilege('anon','resolve_quest_raid_encounter_v1(uuid)','EXECUTE') v`),false);
await db.close();console.log('PASS: approved 10% settings/no-first-guarantee/11th, cap, replay, x2 real Clear+Rescue issuer SQL, grants match Present, same-user Clear+Rescue, manual x1, delivery rollback, legacy bonus excluded. Existing eligibility services are contract doubles.');
