import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url));
const {PGlite}=createRequire(resolve(process.env.RAID_TEST_RUNTIME??root,'package.json'))('@electric-sql/pglite');
const db=new PGlite();
const uid='00000000-0000-0000-0000-000000000001';
const sqlFile=n=>readFileSync(resolve(root,'supabase/migrations',n),'utf8');
const value=async(sql,args=[]) => (await db.query(sql,args)).rows[0]?.value;
// 指定旧関数定義を境界で切り出す。本文を書換えず新Migration前の依存として使用。
function oldFunction(file,name){const text=sqlFile(file);const start=text.indexOf(`create or replace function public.${name}(`);assert.ok(start>=0,name);const body=text.indexOf('$$',start);const end=text.indexOf('$$;',body+2);assert.ok(end>body,name);return text.slice(start,end+3);}
const m210='20260830000210_canonical_master_freeze_runtime.sql';
async function isolated(fn){await db.exec('begin');try{await db.query("select set_config('request.jwt.claim.sub',$1,true)",[uid]);await fn();}finally{await db.exec('rollback');}}
async function rejected(fn,code){await db.exec('savepoint expected_error');try{await assert.rejects(fn,e=>e.code===code);}finally{await db.exec('rollback to savepoint expected_error; release savepoint expected_error');}}
async function boss(room=false){const id=await value("insert into raid_bosses(boss_id,boss_master_id,raid_variant_id,current_hp,max_hp,status,spawned_at,expires_at,base_id,rotation_date,raid_day_key) values('BOSS_A','BOSS_A','BOSS_A',1000,1000,'ACTIVE',now()-interval '1 hour',now()+interval '23 hours','shinjuku',(now() at time zone 'Asia/Tokyo')::date,(now() at time zone 'Asia/Tokyo')::date::text) returning id as value");if(room)await value('select _raid_room_register_v1($1,$2,\'beginner\') as value',[id,uid]);return id;}
const start=id=>value("select start_raid_battle($1,array['fixture-player']) as value",[id]);
async function replay(id){return value("insert into battle_replay_sessions(requester_user_id,battle_mode,source_reference_id,resolution_authority,finalization_status,official_context) values($1,'RAID',$2,'RAID_SERVER','PENDING','{\"costType\":\"RAID_POINT\"}') returning id as value",[uid,id]);}
const result=damage=>({playerRawDamage:damage,events:[{index:0,round:1,type:'DAMAGE',payload:{amount:damage}}]});
const finalize=(id,damage=100)=>value('select finalize_raid_battle($1,$2::jsonb) as value',[id,JSON.stringify(result(damage))]);
async function snapshot(){const out={};for(const t of ['users','raid_bosses','raid_rooms','raid_room_members','battle_replay_sessions','battle_replay_events','raid_damage_logs','raid_instance_user_progress','presents','raid_clear_reward_claims','raid_clear_reward_deliveries','canonical_daily_activity_claims','raid_reward_grants','raid_production_reward_grants','isolation_calls'])out[t]=await value(`select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text),'[]') as value from ${t} t`);return out;}
before(async()=>{
 for(const f of ['raid-room-read-projection-fixture.sql','raid-room-lifecycle-fixture.sql','raid-room-creation-fixture.sql','raid-room-legacy-isolation-fixture.sql'])await db.exec(readFileSync(new URL(f,import.meta.url),'utf8'));
 for(const f of ['20260908000250_raid_room_read_projection.sql','20260908000251_raid_room_condition_rules.sql','20260908000252_raid_room_lifecycle.sql','20260908000253_raid_room_creation.sql'])await db.exec(sqlFile(f));
 for(const name of ['canonical_raid_rotation_pair','on_canonical_daily_activity_finalized'])await db.exec(oldFunction(m210,name));
 await db.exec('create trigger canonical_daily_activity_finalized after update of finalization_status on battle_replay_sessions for each row execute function on_canonical_daily_activity_finalized()');
 await db.exec(sqlFile('20260908000254_raid_room_legacy_isolation.sql'));
 console.log('SQL engine:',await value('select version() as value'));
});
after(()=>db.close());
test('生成フラグは停止のまま',async()=>assert.equal(await value('select enabled as value from raid_room_creation_settings'),false));
test('Roomの旧開始は初回無料/通常RPとも拒否し全台帳に副作用なし',()=>isolated(async()=>{const id=await boss(true);for(const used of [false,true]){await db.query('update users set raid_free_entry_consumed=$1 where id=$2',[used,uid]);const before=await snapshot();await rejected(()=>start(id),'55000');assert.deepEqual(await snapshot(),before);}}));
test('Roomの旧確定は通常/致死Damageとも拒否しtriggerも発火しない',()=>isolated(async()=>{const id=await boss(true),r=await replay(id);for(const damage of [100,10000]){const before=await snapshot();await rejected(()=>finalize(r,damage),'55000');assert.deepEqual(await snapshot(),before);}}));
test('既確定Replayの再取得はRoomでも保存結果だけを返す',()=>isolated(async()=>{const id=await boss(true);const r=await value("insert into battle_replay_sessions(requester_user_id,battle_mode,source_reference_id,resolution_authority,finalization_status,status,finalization_result) values($1,'RAID',$2,'RAID_SERVER','FINALIZED','RESOLVED','{\"saved\":true}') returning id as value",[uid,id]);const before=await snapshot();assert.deepEqual(await finalize(r),{saved:true});assert.deepEqual(await snapshot(),before);}));
test('Roomの旧終了は期限/HP0/既撃破でも状態と報酬を変更しない',()=>isolated(async()=>{const id=await boss(true);for(const change of ["expires_at=now()-interval '1 second'","current_hp=0","status='CLEARED',respawn_after=now()-interval '1 minute'"]){await db.query(`update raid_bosses set ${change} where id=$1`,[id]);const before=await snapshot();await db.query('select finalize_expired_raid_instance($1)',[id]);assert.deepEqual(await snapshot(),before);assert.equal(await value('select respawn_cleared_raid_slot($1) as value',[id]),null);assert.deepEqual(await snapshot(),before);}}));
test('Roomの3種旧報酬直接呼出しは付与0',()=>isolated(async()=>{const id=await boss(true);await db.query("update raid_bosses set current_hp=0,status='CLEARED' where id=$1",[id]);await db.query('insert into raid_instance_user_progress(raid_boss_instance_id,user_id,finalized_battles) values($1,$2,1)',[id,uid]);const before=await snapshot();assert.equal((await value('select grant_canonical_raid_day_clear_reward($1,$2) as value',[id,uid])).eligible,false);assert.equal(await value("select grant_canonical_raid_reward($1,$2,'PROGRESS','1') as value",[id,uid]),0);assert.equal(await value("select grant_raid_reward($1,$2,1,'TEST') as value",[id,uid]),false);assert.deepEqual(await snapshot(),before);}));
test('旧Instance開始は初回無料とRP1、Snapshotを維持',()=>isolated(async()=>{const id=await boss();const a=await start(id);assert.equal(a.cost,0);assert.equal(a.cost_type,'FREE_FIRST');const b=await start(id);assert.equal(b.cost,1);assert.equal(b.cost_type,'RAID_POINT');assert.equal(await value('select raid_points as value from users where id=$1',[uid]),8);assert.equal(b.enemy_snapshot.length,1);assert.equal(await value('select count(*)::int as value from battle_replay_sessions'),2);}));
test('旧Instance開始の認証/Lv/RP/期限拒否は維持',()=>isolated(async()=>{const id=await boss();await db.exec("select set_config('request.jwt.claim.sub','',true)");await rejected(()=>start(id),'42501');await db.query("select set_config('request.jwt.claim.sub',$1,true)",[uid]);await db.query('update users set level=4 where id=$1',[uid]);await rejected(()=>start(id),'23514');await db.query('update users set level=5,raid_free_entry_consumed=true,raid_points=0 where id=$1',[uid]);await rejected(()=>start(id),'23514');await db.query('update users set raid_points=5 where id=$1',[uid]);await db.query("update raid_bosses set expires_at=now()-interval '1 second' where id=$1",[id]);await rejected(()=>start(id),'P0002');}));
test('旧確定はHP/log/progress/event/ミッション/実日次triggerを更新し再送は冪等',()=>isolated(async()=>{const id=await boss(),r=await replay(id);const f=await finalize(r);assert.equal(f.remainingBossHp,900);assert.equal(f.rawDamage,100);for(const t of ['raid_damage_logs','battle_replay_events','raid_instance_user_progress','canonical_daily_activity_claims','presents'])assert.equal(await value(`select count(*)::int as value from ${t}`),1,t);assert.equal(await value("select count(*)::int as value from isolation_calls where kind='mission'"),1);const before=await snapshot();assert.deepEqual(await finalize(r),f);assert.deepEqual(await snapshot(),before);}));
test('旧3戦/RP5の日次triggerは維持',()=>isolated(async()=>{const id=await boss();for(let i=0;i<5;i++)await finalize(await replay(id),1);assert.equal(await value("select count(*)::int as value from canonical_daily_activity_claims where source_key='RAID_DAILY_3'"),1);assert.equal(await value("select count(*)::int as value from canonical_daily_activity_claims where source_key='RAID_POINTS_5'"),1);}));
test('旧撃破はclipping/clear台帳/respawnを維持、再呼出しで付与重複なし',()=>isolated(async()=>{const id=await boss();const f=await finalize(await replay(id),1200);assert.equal(f.appliedDamage,1000);assert.equal(await value('select status as value from raid_bosses where id=$1',[id]),'CLEARED');assert.equal(await value('select count(*)::int as value from raid_clear_reward_claims'),1);const before=await snapshot();await db.query('select finalize_expired_raid_instance($1)',[id]);assert.deepEqual(await snapshot(),before);await db.query("update raid_bosses set respawn_after=now()-interval '1 minute' where id=$1",[id]);assert.ok(await value('select respawn_cleared_raid_slot($1) as value',[id]));assert.equal(await value('select respawn_cleared_raid_slot($1) as value',[id]),null);}));
test('旧期限終了はEXPIRED、旧2種grantは従来どおり一度付与',()=>isolated(async()=>{const id=await boss();await db.query("update raid_bosses set expires_at=now()-interval '1 second' where id=$1",[id]);await db.query('select finalize_expired_raid_instance($1)',[id]);assert.equal(await value('select status as value from raid_bosses where id=$1',[id]),'EXPIRED');assert.equal(await value("select grant_canonical_raid_reward($1,$2,'PROGRESS','1') as value",[id,uid]),1);assert.equal(await value("select grant_canonical_raid_reward($1,$2,'PROGRESS','1') as value",[id,uid]),0);assert.equal(await value("select grant_raid_reward($1,$2,1,'TEST') as value",[id,uid]),true);assert.equal(await value("select grant_raid_reward($1,$2,1,'TEST') as value",[id,uid]),false);}));
test('rotationと旧一覧はRoomを除外、同エリアRoomは旧2枠生成を塞がない',()=>isolated(async()=>{
 const pair=await value("select canonical_raid_rotation_pair((now() at time zone 'Asia/Tokyo')::date) as value");
 await db.query("update canonical_raid_variants set area_id=upper($1) where raid_variant_id='BOSS_A'",[pair[0]]);await db.query("update canonical_raid_variants set area_id=upper($1) where raid_variant_id='BOSS_B'",[pair[1]]);
 const id=await boss(true);await db.query('update raid_bosses set base_id=$1 where id=$2',[pair[0],id]);
 const roomBefore=await value('select to_jsonb(b) as value from raid_bosses b where id=$1',[id]);
 const list=await value('select get_active_raids() as value');assert.equal(list.length,2);assert.ok(list.every(b=>b.id!==id));assert.deepEqual(await value('select to_jsonb(b) as value from raid_bosses b where id=$1',[id]),roomBefore);
 await db.query("update raid_bosses set current_hp=0,expires_at=now()-interval '1 second' where id=$1",[id]);const ended=await value('select to_jsonb(b) as value from raid_bosses b where id=$1',[id]);await db.exec('select rotate_daily_raids()');assert.deepEqual(await value('select to_jsonb(b) as value from raid_bosses b where id=$1',[id]),ended);
}));
test('旧writerのauthenticated実行拒否、service_role確定権限',()=>isolated(async()=>{for(const fn of ['finalize_raid_battle(uuid,jsonb)','grant_canonical_raid_day_clear_reward(uuid,uuid)','grant_canonical_raid_reward(uuid,uuid,text,text)','grant_raid_reward(uuid,uuid,integer,text)']){assert.equal(await value("select has_function_privilege('authenticated',$1,'EXECUTE') as value",[fn]),false);assert.equal(await value("select has_function_privilege('service_role',$1,'EXECUTE') as value",[fn]),true);}}));
