import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomUUID} from 'node:crypto';
const root=fileURLToPath(new URL('../../',import.meta.url));
const {PGlite}=createRequire(resolve(process.env.RAID_TEST_RUNTIME??root,'package.json'))('@electric-sql/pglite');
const db=new PGlite();
const uid=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const value=async(sql,args=[]) => (await db.query(sql,args)).rows[0]?.value;
async function create(difficulty='beginner'){
 const r=await value("select create_raid_room_v1($1,'BOSS_A',$2) as value",[difficulty,randomUUID()]);
 // 実APIの別transactionを模す。外側rollback内ではnow()が生成clock_timestampより前なので時刻を補正。
 await admin();await db.query("update raid_bosses set spawned_at=now()-interval '1 second',expires_at=now()+interval '24 hours'-interval '1 second' where id=(select raid_boss_instance_id from raid_rooms where id=$1)",[r.roomId]);await asUser();return r;
}
const join=id=>value('select register_raid_room_v1($1) as value',[id]);
const brief=id=>value('select get_raid_room_briefing_v1($1) as value',[id]);
const start=(id,request=randomUUID(),ids=['fixture-player'],tactic='BALANCED')=>value('select start_raid_room_battle_v1($1,$2::text[],$3,$4) as value',[id,ids,tactic,request]);
async function asUser(n=1){await db.query("select set_config('request.jwt.claim.sub',$1,true)",[n===null?'':uid(n)]);await db.exec('set local role authenticated');}
async function admin(){await db.exec('reset role');}
async function isolated(fn){await db.exec('begin');try{await db.exec('update raid_room_creation_settings set enabled=true');await asUser();await fn();}finally{await db.exec('rollback');}}
async function rejected(fn,code){await db.exec('savepoint expected_error');try{await assert.rejects(fn,e=>!code||e.code===code);}finally{await db.exec('rollback to savepoint expected_error; release savepoint expected_error');}}
async function enabled(){await admin();await db.exec('update raid_room_battle_settings set enabled=true');await asUser();}
async function snapshot(){await admin();const out={};for(const t of ['users','raid_bosses','raid_rooms','raid_room_members','battle_replay_sessions','battle_replay_events','raid_damage_logs','raid_instance_user_progress','presents','isolation_calls','raid_room_battle_start_requests'])out[t]=await value(`select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text),'[]') as value from ${t} t`);await asUser();return out;}
async function setPower(power,n=2){await admin();await db.query('update creation_fixture_power set power=$1 where user_id=$2',[power,uid(n)]);await asUser(n);}
async function setSnapshot(power,n=1){await admin();await db.query('update entry_fixture_snapshots set payload=$1 where user_id=$2',[JSON.stringify([{id:'fixture-player',stats:{hp:power,atk:0,def:0}}]),uid(n)]);await asUser(n);}
before(async()=>{
 for(const f of ['raid-room-read-projection-fixture.sql','raid-room-lifecycle-fixture.sql','raid-room-creation-fixture.sql','raid-room-legacy-isolation-fixture.sql','raid-room-entry-fixture.sql','raid-room-finalization-fixture.sql'])await db.exec(readFileSync(new URL(f,import.meta.url),'utf8'));
 const dir=resolve(root,'supabase/migrations');
 const validation=readFileSync(resolve(dir,'20260813000144_official_battle_replay_contract.sql'),'utf8').match(/create or replace function public\.validate_official_battle_result[\s\S]*?\$\$;/)[0];
 await db.exec(validation);
 for(const f of readdirSync(dir).filter(f=>/^2026090800025[0-6]_/.test(f)).sort())await db.exec(readFileSync(resolve(dir,f),'utf8'));
 await db.exec(`create trigger canonical_daily_activity_finalized after update of finalization_status on public.battle_replay_sessions for each row execute function public.on_canonical_daily_activity_finalized(); create trigger canonical_guild_official_battle_exp_trigger after update of finalization_status on public.battle_replay_sessions for each row execute function public.on_canonical_guild_official_battle_exp(); create trigger ranking_daily_participation_capture after update of finalization_status on public.battle_replay_sessions for each row execute function public.capture_daily_ranking_participation();`);
 console.log('SQL engine:',await value('select version() as value'));
});
after(()=>db.close());

const result=(raw=100)=>({winner:'ENEMY',rounds:1,enemyRawDamage:100,playerRawDamage:raw,events:[{index:0,round:1,type:'DAMAGE',payload:{damage:raw}}]});
async function service(){await admin();await db.exec('set local role service_role');}
const finalize=(id,raw=100)=>value('select finalize_raid_room_battle_v1($1,$2::jsonb) as value',[id,JSON.stringify(result(raw))]);
const route=id=>value('select get_raid_battle_route_v1($1) as value',[id]);
const ownResult=id=>value('select get_raid_room_battle_result_v1($1) as value',[id]);
async function prepared(){const r=await create();await enabled();const s=await start(r.roomId);await service();return {...r,...s};}
async function state(){await admin();const out={};for(const t of ['raid_bosses','raid_instance_user_progress','raid_damage_logs','battle_replay_sessions','battle_replay_events','presents','canonical_daily_activity_claims','ranking_daily_participation','isolation_calls'])out[t]=await value(`select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text),'[]') as value from ${t} t`);await service();return out;}
async function changeBoss(roomId,assignment){await admin();await db.query(`update raid_bosses set ${assignment} where id=(select raid_boss_instance_id from raid_rooms where id=$1)`,[roomId]);if(assignment.includes('expires_at='))await db.query("update battle_replay_sessions set official_context=jsonb_set(official_context,'{startedAt}',to_jsonb((clock_timestamp()-interval '2 seconds')::text)) where source_reference_id=(select raid_boss_instance_id from raid_rooms where id=$1)",[roomId]);await service();}
test('期限前確定はHP減少とraw貢献を1回保存',()=>isolated(async()=>{const r=await prepared();assert.equal(await route(r.replay_session_id),'ROOM');const f=await finalize(r.replay_session_id,300);assert.equal(f.rawDamage,300);assert.equal(f.appliedDamage,300);assert.equal(f.personalContribution,300);assert.equal(f.remainingBossHp,28000000-300);await admin();assert.equal(await value('select count(*)::int as value from battle_replay_events'),1);assert.equal(await value('select finalized_battles as value from raid_instance_user_progress'),1);}));
test('期限経過後確定はraw保存・applied0・HP不変',()=>isolated(async()=>{const r=await prepared();await changeBoss(r.roomId,"expires_at=clock_timestamp()-interval '1 second'");const f=await finalize(r.replay_session_id,500);assert.equal(f.rawDamage,500);assert.equal(f.appliedDamage,0);assert.equal(f.personalContribution,500);assert.equal(f.remainingBossHp,28000000);await admin();assert.equal(await value('select raw_damage::int as value from raid_damage_logs'),500);}));
test('撃破は残HPでclipping、その後の別戦はrawのみ保存',()=>isolated(async()=>{const r=await prepared();await asUser();const b=await start(r.roomId);await changeBoss(r.roomId,'current_hp=50');const f=await finalize(r.replay_session_id,100);assert.equal(f.appliedDamage,50);assert.equal(f.remainingBossHp,0);await admin();const cleared=await value('select to_jsonb(b) as value from raid_bosses b');assert.equal(cleared.outcome,'DEFEAT_SUCCESS');assert.ok(cleared.cleared_at);await service();const g=await finalize(b.replay_session_id,200);assert.equal(g.appliedDamage,0);assert.equal(g.personalContribution,300);await admin();assert.deepEqual(await value('select to_jsonb(b) as value from raid_bosses b'),cleared);assert.equal(await value('select sum(applied_damage)::int as value from raid_damage_logs'),50);}));
test('同Replay再確定は保存結果だけ返し全台帳不変',()=>isolated(async()=>{const r=await prepared();const f=await finalize(r.replay_session_id);const prev=await state();assert.deepEqual(await finalize(r.replay_session_id,9999),f);assert.deepEqual(await state(),prev);}));
test('本人はPENDING null・確定結果取得、別人と匿名は拒否',()=>isolated(async()=>{const r=await prepared();await asUser();assert.equal(await ownResult(r.replay_session_id),null);await service();const f=await finalize(r.replay_session_id);await asUser();assert.deepEqual(await ownResult(r.replay_session_id),f);await asUser(2);await rejected(()=>ownResult(r.replay_session_id));await asUser(null);await rejected(()=>ownResult(r.replay_session_id));}));
test('公開ロールは確定・route・期限終了RPC実行不可',()=>isolated(async()=>{const r=await prepared();for(const role of ['anon','authenticated']){await admin();await db.exec('set local role '+role);await rejected(()=>finalize(r.replay_session_id),'42501');await rejected(()=>route(r.replay_session_id),'42501');await rejected(()=>value('select finalize_expired_raid_room_v1($1) as value',[r.roomId]),'42501');}}));
test('Room確定は旧daily PresentとGuild報酬を発行しない',()=>isolated(async()=>{const r=await prepared();await finalize(r.replay_session_id);await admin();assert.equal(await value('select count(*)::int as value from presents'),0);assert.equal(await value('select count(*)::int as value from canonical_daily_activity_claims'),0);assert.equal(await value("select count(*)::int as value from isolation_calls where kind like 'guild:%'"),0);}));
test('開始receiptがないRoom Replayは確定とrouteを拒否',()=>isolated(async()=>{const r=await prepared();await admin();await db.query('delete from raid_room_battle_start_requests where replay_session_id=$1',[r.replay_session_id]);await service();await rejected(()=>route(r.replay_session_id));await rejected(()=>finalize(r.replay_session_id));}));
async function legacy(){await admin();const id=randomUUID(),bid=randomUUID();await db.query("insert into raid_bosses(id,boss_id,boss_master_id,base_id,raid_variant_id,raid_day_key,current_hp,max_hp,status,spawned_at,expires_at) values($1,'BOSS_A','BOSS_A','shinjuku','BOSS_A',(now() at time zone 'Asia/Tokyo')::date::text,28000000,28000000,'ACTIVE',now()-interval '1 hour',now()+interval '1 day')",[bid]);await db.query("insert into battle_replay_sessions(id,requester_user_id,battle_mode,source_reference_id,resolution_authority,finalization_status,official_context) values($1,$2,'RAID',$3,'RAID_SERVER','PENDING','{\"costType\":\"RAID_POINT\"}')",[id,uid(1),bid]);await service();return id;}
test('非RoomはLEGACY route、旧確定とdaily/Guild triggerを維持',()=>isolated(async()=>{const id=await legacy();assert.equal(await route(id),'LEGACY');const f=await value('select finalize_raid_battle($1,$2::jsonb) as value',[id,JSON.stringify(result(100))]);assert.equal(f.appliedDamage,100);await admin();assert.equal(await value('select count(*)::int as value from presents'),1);assert.equal(await value("select count(*)::int as value from isolation_calls where kind='guild:RAID_FINALIZED'"),1);}));
test('Room戦を旧3戦daily集計へ混ぜない',()=>isolated(async()=>{const r=await prepared();await finalize(r.replay_session_id);await asUser();const b=await start(r.roomId);await service();await finalize(b.replay_session_id);const old=await legacy();await value('select finalize_raid_battle($1,$2::jsonb) as value',[old,JSON.stringify(result())]);await admin();assert.equal(await value("select count(*)::int as value from canonical_daily_activity_claims where source_key='RAID_DAILY_3'"),0);assert.equal(await value('select count(*)::int as value from presents'),1);}));
test('期限終了処理は期限前不変・期限後再送で不変',()=>isolated(async()=>{const r=await prepared();const prev=await state();await value('select finalize_expired_raid_room_v1($1) as value',[r.roomId]);assert.deepEqual(await state(),prev);await changeBoss(r.roomId,"expires_at=clock_timestamp()-interval '1 second'");await value('select finalize_expired_raid_room_v1($1) as value',[r.roomId]);const ended=await state();await value('select finalize_expired_raid_room_v1($1) as value',[r.roomId]);assert.deepEqual(await state(),ended);await finalize(r.replay_session_id);await admin();assert.equal(await value('select applied_damage::int as value from raid_damage_logs'),0);}));
test('非Room ReplayをRoom確定へ渡しても旧HP/台帳を変更しない',()=>isolated(async()=>{const id=await legacy(),prev=await state();await rejected(()=>finalize(id));assert.deepEqual(await state(),prev);}));

test('Room確定は旧ranking参加台帳へ入らず非Roomのみ加算',()=>isolated(async()=>{const r=await prepared();await finalize(r.replay_session_id);await admin();assert.equal(await value('select count(*)::int as value from ranking_daily_participation'),0);const id=await legacy();await value('select finalize_raid_battle($1,$2::jsonb) as value',[id,JSON.stringify(result())]);await admin();assert.equal(await value('select finalized_count as value from ranking_daily_participation'),1);}));
test('Room metadata偽装・receipt requester不一致はrouteと確定で拒否',()=>isolated(async()=>{for(const mode of ['metadata','requester']){const r=await prepared();await admin();if(mode==='metadata')await db.query("update battle_replay_sessions set official_context=jsonb_set(official_context,'{roomId}',to_jsonb($2::text)) where id=$1",[r.replay_session_id,randomUUID()]);else await db.query('update raid_room_battle_start_requests set user_id=$2 where replay_session_id=$1',[r.replay_session_id,uid(2)]);await service();await rejected(()=>route(r.replay_session_id),'23514');await rejected(()=>finalize(r.replay_session_id),'23514');await asUser();}}));
test('ranking lifecycle hookは新Roomで呼ばず旧非Room確定で維持',()=>isolated(async()=>{const r=await prepared();await finalize(r.replay_session_id);await admin();assert.equal(await value("select count(*)::int as value from isolation_calls where kind='ranking:RAID'"),0);const id=await legacy();await value('select finalize_raid_battle($1,$2::jsonb) as value',[id,JSON.stringify(result())]);await admin();assert.equal(await value("select count(*)::int as value from isolation_calls where kind='ranking:RAID'"),1);}));

test('既存実validate関数が不正Resultを拒否し確定副作用なし',()=>isolated(async()=>{const r=await prepared(),prev=await state();for(const payload of [{...result(),rounds:0},{...result(),playerRawDamage:-1},{...result(),events:{}},{...result(),winner:'UNKNOWN'}])await rejected(()=>value('select finalize_raid_room_battle_v1($1,$2::jsonb) as value',[r.replay_session_id,JSON.stringify(payload)]),'22023');assert.deepEqual(await state(),prev);}));
