import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomUUID} from 'node:crypto';
const root=fileURLToPath(new URL('../../',import.meta.url));
const {PGlite}=createRequire(resolve(process.env.RAID_TEST_RUNTIME??root,'package.json'))('@electric-sql/pglite');
const db=new PGlite();
const uid=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const value=async(sql,args=[]) => (await db.query(sql,args)).rows[0]?.value;
async function create(difficulty='beginner'){
 const r=await value("select create_raid_room_v1($1,'BOSS_A',$2) as value",[difficulty,randomUUID()]);
 // 実APIの別transactionを模す。外側rollback内ではnow()が生成clock_timestampより前なので時刻を補正。
 await admin();await db.query("update raid_bosses set spawned_at=now()-interval '1 second',expires_at=now()+interval '24 hours'-interval '1 second' where id=(select raid_boss_instance_id from raid_rooms where id=$1)",[r.roomId]);await asUser();return r;
}
const join=id=>value('select register_raid_room_v1($1) as value',[id]);
const brief=id=>value('select get_raid_room_briefing_v1($1) as value',[id]);
const start=(id,request=randomUUID(),ids=['fixture-player'],tactic='BALANCED')=>value('select start_raid_room_battle_v1($1,$2::text[],$3,$4) as value',[id,ids,tactic,request]);
async function asUser(n=1){await db.query("select set_config('request.jwt.claim.sub',$1,true)",[n===null?'':uid(n)]);await db.exec('set local role authenticated');}
async function admin(){await db.exec('reset role');}
async function isolated(fn){await db.exec('begin');try{await db.exec('update raid_room_creation_settings set enabled=true');await asUser();await fn();}finally{await db.exec('rollback');}}
async function rejected(fn,code){await db.exec('savepoint expected_error');try{await assert.rejects(fn,e=>!code||e.code===code);}finally{await db.exec('rollback to savepoint expected_error; release savepoint expected_error');}}
async function enabled(){await admin();await db.exec('update raid_room_battle_settings set enabled=true');await asUser();}
async function snapshot(){await admin();const out={};for(const t of ['users','raid_bosses','raid_rooms','raid_room_members','battle_replay_sessions','battle_replay_events','raid_damage_logs','raid_instance_user_progress','presents','isolation_calls','raid_room_battle_start_requests'])out[t]=await value(`select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text),'[]') as value from ${t} t`);await asUser();return out;}
async function setPower(power,n=2){await admin();await db.query('update creation_fixture_power set power=$1 where user_id=$2',[power,uid(n)]);await asUser(n);}
async function setSnapshot(power,n=1){await admin();await db.query('update entry_fixture_snapshots set payload=$1 where user_id=$2',[JSON.stringify([{id:'fixture-player',stats:{hp:power,atk:0,def:0}}]),uid(n)]);await asUser(n);}
before(async()=>{
 for(const f of ['raid-room-read-projection-fixture.sql','raid-room-lifecycle-fixture.sql','raid-room-creation-fixture.sql','raid-room-legacy-isolation-fixture.sql','raid-room-entry-fixture.sql'])await db.exec(readFileSync(new URL(f,import.meta.url),'utf8'));
 const dir=resolve(root,'supabase/migrations');
 for(const f of readdirSync(dir).filter(f=>/^2026090800025[0-5]_/.test(f)).sort())await db.exec(readFileSync(resolve(dir,f),'utf8'));
 console.log('SQL engine:',await value('select version() as value'));
});
after(()=>db.close());
test('停止設定で開始拒否、全台帳と資産に副作用なし',()=>isolated(async()=>{const r=await create();const prev=await snapshot();await rejected(()=>start(r.roomId),'55000');assert.deepEqual(await snapshot(),prev);}));
test('他ユーザーへ公開参照とbriefing、未参加で総合力条件を提示',()=>isolated(async()=>{const r=await create('intermediate');await asUser(2);const b=await brief(r.roomId);assert.equal(b.membershipStatus,'not_joined');assert.equal(b.joinEligibility.status,'passed');assert.equal(b.battleStartEnabled,false);assert.ok(b.raidBossInstanceId);assert.equal(b.raidVariantId,'BOSS_A');const dto=await value('select get_raid_room_v1($1) as value',[r.roomId]);assert.equal(dto.roomId,r.roomId);}));
test('匿名は参加・briefing・開始を拒否',()=>isolated(async()=>{const r=await create();await asUser(null);for(const fn of [()=>brief(r.roomId),()=>join(r.roomId),()=>start(r.roomId)])await rejected(fn,'42501');await admin();await db.exec('set local role anon');for(const fn of [()=>brief(r.roomId),()=>join(r.roomId),()=>start(r.roomId)])await rejected(fn,'42501');}));
test('参加は本人台帳のみ、再送で人数と消費を増やさない',()=>isolated(async()=>{const r=await create();await asUser(2);await admin();const assets=await value('select jsonb_agg(u order by id) as value from users u');await asUser(2);const a=await join(r.roomId);assert.equal(a.membershipStatus,'joined');await admin();assert.deepEqual(await value('select jsonb_agg(u order by id) as value from users u'),assets);await asUser(2);const prev=await snapshot();await asUser(2);assert.equal((await join(r.roomId)).membershipStatus,'already_joined');assert.deepEqual(await snapshot(),prev);await asUser(2);assert.equal((await brief(r.roomId)).membershipStatus,'joined');}));
for(const [difficulty,min] of [['intermediate',160000],['advanced',200000],['expert',240000]])test(`${difficulty}参加Main下限の直前・一致・直後`,()=>isolated(async()=>{const r=await create(difficulty);await setPower(min-1);assert.equal((await brief(r.roomId)).joinEligibility.status,'failed');await rejected(()=>join(r.roomId));await setPower(min);assert.equal((await join(r.roomId)).membershipStatus,'joined');await setPower(min+1,3);assert.equal((await join(r.roomId)).membershipStatus,'joined');}));
test('Lv4とプロフィール不在は参加拒否、Lv5許可',()=>isolated(async()=>{const r=await create();await admin();await db.query('update users set level=4 where id=$1',[uid(2)]);await asUser(2);await rejected(()=>join(r.roomId));await asUser(99);await rejected(()=>join(r.roomId));await admin();await db.query('update users set level=5 where id=$1',[uid(2)]);await asUser(2);assert.equal((await join(r.roomId)).membershipStatus,'joined');}));
test('主催者含む20人上限、21人目は参加台帳を増やさない',()=>isolated(async()=>{const r=await create();for(let n=2;n<=20;n++){await asUser(n);await join(r.roomId);}const prev=await snapshot();await asUser(21);await rejected(()=>join(r.roomId));assert.deepEqual(await snapshot(),prev);}));
test('期限経過・撃破Roomは新規参加不可',()=>isolated(async()=>{for(const change of ["expires_at=clock_timestamp()-interval '1 second'","current_hp=0"]){const r=await create();await admin();await db.query(`update raid_bosses set ${change} where id=(select raid_boss_instance_id from raid_rooms where id=$1)`,[r.roomId]);await asUser(2);await rejected(()=>join(r.roomId));await asUser();}}));
test('開始は初回無料と以後RP1、RoomつきSnapshot receiptを保存',()=>isolated(async()=>{const r=await create();await enabled();const a=await start(r.roomId);assert.equal(a.cost,0);assert.equal(a.cost_type,'FREE_FIRST');assert.equal(a.room_id,r.roomId);assert.equal(a.enemy_snapshot.length,5);await admin();const ctx=await value('select official_context as value from battle_replay_sessions where id=$1',[a.replay_session_id]);assert.equal(ctx.roomId,r.roomId);assert.equal(ctx.difficultyId,'beginner');assert.equal(ctx.formationPower,300000);assert.ok(ctx.roomExpiresAt);assert.ok(ctx.startedAt);await asUser();const b=await start(r.roomId);assert.equal(b.cost,1);assert.equal(b.cost_type,'RAID_POINT');await admin();assert.equal(await value('select raid_points as value from users where id=$1',[uid(1)]),8);assert.equal(await value('select count(*)::int as value from battle_replay_sessions'),2);}));
test('開始同request同payload再送は同receipt、二重消費なし',()=>isolated(async()=>{const r=await create();await enabled();const req=randomUUID(),a=await start(r.roomId,req),prev=await snapshot();assert.deepEqual(await start(r.roomId,req),a);assert.deepEqual(await snapshot(),prev);await rejected(()=>start(r.roomId,req,['other']));await rejected(()=>start(r.roomId,req,['fixture-player'],'ATTACK_PRIORITY'),'22023');}));
for(const [difficulty,min] of [['intermediate',160000],['advanced',200000],['expert',240000]])test(`${difficulty}開始は実Snapshot下限の直前拒否・一致と直後許可`,()=>isolated(async()=>{const r=await create(difficulty);await enabled();await setSnapshot(min-1);const prev=await snapshot();await rejected(()=>start(r.roomId));assert.deepEqual(await snapshot(),prev);await setSnapshot(min);assert.ok(await start(r.roomId));await setSnapshot(min+1);assert.ok(await start(r.roomId));}));
test('開始は未参加・別人のrequestでも本人参加と消費を検証',()=>isolated(async()=>{const r=await create();await enabled();const req=randomUUID(),a=await start(r.roomId,req);await asUser(2);await rejected(()=>start(r.roomId,req));await join(r.roomId);const b=await start(r.roomId,req);assert.notDeepEqual(a,b);await admin();assert.equal(await value('select count(distinct requester_user_id)::int as value from battle_replay_sessions'),2);}));
test('空・重複・非所有編成を拒否し消費0',()=>isolated(async()=>{const r=await create();await enabled();const prev=await snapshot();for(const ids of [[],null,['fixture-player','fixture-player'],['not-owned']])await rejected(()=>start(r.roomId,randomUUID(),ids));assert.deepEqual(await snapshot(),prev);}));
test('RP不足・終了後新規開始は消費とReplayを増やさない',()=>isolated(async()=>{const r=await create();await enabled();await admin();await db.query('update users set raid_free_entry_consumed=true,raid_points=0 where id=$1',[uid(1)]);await asUser();let prev=await snapshot();await rejected(()=>start(r.roomId));assert.deepEqual(await snapshot(),prev);await admin();await db.query("update users set raid_points=5 where id=$1",[uid(1)]);await db.query("update raid_bosses set expires_at=clock_timestamp()-interval '1 second' where id=(select raid_boss_instance_id from raid_rooms where id=$1)",[r.roomId]);await asUser();prev=await snapshot();await rejected(()=>start(r.roomId));assert.deepEqual(await snapshot(),prev);}));
test('公開一覧と詳細は見えるが未参加の参加者一覧は非公開',()=>isolated(async()=>{const r=await create();await asUser(2);assert.ok(await value("select list_raid_rooms_v1('beginner',20,0) as value"));await rejected(()=>value('select get_raid_room_participants_v1($1,20,0) as value',[r.roomId]),'P0002');await join(r.roomId);assert.ok(await value('select get_raid_room_participants_v1($1,20,0) as value',[r.roomId]));}));
test('不正Snapshot型・欠損・負・小数・HP0・重複IDは消費前に拒否',()=>isolated(async()=>{const r=await create();await enabled();for(const payload of [null,[],[{id:'fixture-player',stats:{hp:0,atk:1,def:1}}],[{id:'fixture-player',stats:{hp:1,atk:-1,def:1}}],[{id:'fixture-player',stats:{hp:1,atk:1.5,def:1}}],[{id:'fixture-player',stats:{hp:'300000',atk:1,def:1}}],[{id:'fixture-player',stats:{hp:1}}],[{id:'fixture-player',stats:{hp:2147483648,atk:0,def:0}}],[{id:'x',stats:{hp:1,atk:1,def:1}},{id:'x',stats:{hp:1,atk:1,def:1}}]]){await admin();await db.query('update entry_fixture_snapshots set payload=$1 where user_id=$2',[JSON.stringify(payload),uid(1)]);await asUser();const prev=await snapshot();await rejected(()=>start(r.roomId));assert.deepEqual(await snapshot(),prev);}}));
test('開始設定とreceiptへの直接アクセスは公開ロールへ許可しない',()=>isolated(async()=>{await admin();for(const role of ['anon','authenticated','service_role'])for(const table of ['raid_room_battle_settings','raid_room_battle_start_requests'])for(const permission of ['SELECT','INSERT','UPDATE','DELETE'])assert.equal(await value('select has_table_privilege($1,$2,$3) as value',[role,table,permission]),false);}));
test('開始後期限が切れても同request receiptのみ再取得、新Replayなし',()=>isolated(async()=>{const r=await create();await enabled();const req=randomUUID(),a=await start(r.roomId,req);await admin();await db.query("update raid_bosses set expires_at=clock_timestamp()-interval '1 second' where id=(select raid_boss_instance_id from raid_rooms where id=$1)",[r.roomId]);await asUser();const prev=await snapshot();assert.deepEqual(await start(r.roomId,req),a);assert.deepEqual(await snapshot(),prev);}));
