import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const out='docs/development/evidence/raid-character-integration/raid';await mkdir(out,{recursive:true});
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,reducedMotion:"reduce"});const errors=[];page.on('pageerror',error=>errors.push(error.message));
await page.goto(process.env.RAID_DETAIL_QA_URL||'http://127.0.0.1:3015/qa/raid-detail');const report=[];
async function scenario(name){await page.getByLabel('Mockシナリオ',{exact:true}).selectOption(name);if(name==='loading')await page.getByRole('status',{name:'通信中'}).waitFor();else await page.getByTestId('raid-room-detail').waitFor({timeout:30000});await page.evaluate(()=>document.fonts.ready);}
async function capture(name){await page.evaluate(()=>Promise.all(Array.from(document.images).map(img=>img.decode().catch(()=>{}))));await page.screenshot({animations:"disabled",path:`${out}/${name}.png`});}
async function closeDialog(){if(await page.locator('.raid-room-dialogs').count()){const box=await page.locator('.raid-room-dialogs .canonical-dialog-close').boundingBox();assert.ok(box&&box.width>=44&&box.height>=44);}await page.getByRole('dialog').getByRole('button',{name:'閉じる',exact:true}).last().click();}
async function hit(locator){return locator.evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));});}
for(const name of ['owner','member','rescue','not_joined','cleared','expired','loading','error','unknown','many','long-name','no-guild']){
 await scenario(name);await page.locator('.ui-hub-page-scroll').evaluate(el=>el.scrollTop=0);await capture(`detail-${name}-390`);
 const dimensions=await page.locator('.ui-hub-page-content').evaluate(el=>({client:el.clientWidth,scroll:el.scrollWidth}));assert.ok(dimensions.scroll<=dimensions.client+1,`overflow ${name}`);
 await page.locator('.ui-hub-page-scroll').evaluate(el=>el.scrollTop=el.scrollHeight);await capture(`detail-${name}-lower-390`);report.push({name,dimensions});
}
for(const height of [844,600]){
 await page.setViewportSize({width:390,height});await scenario('long-name');await page.locator('.ui-hub-page-scroll').evaluate(el=>el.scrollTop=0);await capture(`detail-long-name-${height}-top`);await page.locator('.ui-hub-page-scroll').evaluate(el=>el.scrollTop=el.scrollHeight);await capture(`detail-long-name-${height}-bottom`);await page.getByRole('button',{name:'参加者一覧',exact:true}).click();await page.getByRole('dialog',{name:'参加者',exact:true}).waitFor();
 const body=page.locator('.raid-room-dialogs .canonical-dialog-body');await body.evaluate(el=>el.scrollTop=600);await capture(`participants-many-${height}`);const row=page.locator('[data-profile-user="qa-person-7"]');await row.scrollIntoViewIfNeeded();const before=await body.evaluate(el=>el.scrollTop);await row.click();await page.getByRole('dialog',{name:/公開プロフィール/}).waitFor();assert.equal(await page.getByRole('dialog').count(),1);await capture(`profile-${height}`);await closeDialog();await page.getByRole('dialog',{name:'参加者',exact:true}).waitFor();const after=await body.evaluate(el=>el.scrollTop);assert.ok(Math.abs(after-before)<=1,`${before} != ${after}`);assert.equal(await page.getByRole('dialog').count(),1);await capture(`participants-restored-${height}`);assert.ok(await hit(page.getByRole('dialog').getByRole('button',{name:'閉じる',exact:true}).last()));await closeDialog();
 for(const name of ['reward-unconfigured','reward-planned','reward-issued','reward-error']){
  await scenario(name);await page.getByRole('button',{name:'報酬',exact:true}).click();await page.getByRole('dialog',{name:'報酬',exact:true}).waitFor();await page.waitForFunction(()=>document.querySelectorAll('.raid-room-dialogs .spinner').length===0);await capture(`${name}-${height}-top`);
  const rewardBody=page.locator('.raid-room-dialogs .canonical-dialog-body');const size=await rewardBody.evaluate(el=>({client:el.clientHeight,scroll:el.scrollHeight,width:el.clientWidth,scrollWidth:el.scrollWidth}));assert.ok(size.scrollWidth<=size.width+1);if(name==='reward-planned'||name==='reward-issued')assert.ok(size.scroll>size.client);
  await rewardBody.evaluate(el=>el.scrollTop=el.scrollHeight);await capture(`${name}-${height}-bottom`);assert.ok(await hit(page.getByRole('dialog').getByRole('button',{name:'閉じる',exact:true}).last()));
  if(name==='reward-issued'){const present=page.getByRole('button',{name:/プレゼントBOX/}).last();await present.scrollIntoViewIfNeeded();assert.ok(await hit(present));await present.click();await page.getByRole('dialog',{name:'導線確認（Mock）'}).waitFor();assert.equal(await page.getByRole('dialog').count(),1);await page.getByRole('button',{name:'戻る',exact:true}).click();}else await closeDialog();
  report.push({name,height,size});
 }
}
await page.getByLabel('実Browser統合',{exact:true}).check();
for(const height of [844,600]){await page.setViewportSize({width:390,height});await scenario('member');await page.locator('.ui-hub-page-scroll').evaluate(el=>el.scrollTop=0);await capture(`integrated-member-${height}-top`);await page.locator('.ui-hub-page-scroll').evaluate(el=>el.scrollTop=el.scrollHeight);await capture(`integrated-member-${height}-bottom`);assert.ok(await hit(page.getByRole('button',{name:'出撃準備',exact:true})));}
await scenario('long-name');await page.getByRole('button',{name:'参加者一覧',exact:true}).click();await page.getByRole('dialog',{name:'参加者',exact:true}).waitFor();await page.locator('.raid-room-dialogs .canonical-dialog-body').evaluate(el=>el.scrollTop=500);await capture('integrated-participants-600');const integratedBody=page.locator('.raid-room-dialogs .canonical-dialog-body');const integratedRow=page.locator('[data-profile-user="qa-person-7"]');await integratedRow.scrollIntoViewIfNeeded();const saved=await integratedBody.evaluate(el=>el.scrollTop);await integratedRow.click();await page.getByRole('dialog',{name:/公開プロフィール/}).waitFor();assert.equal(await page.getByRole('dialog').count(),1);await capture('integrated-profile-600');await closeDialog();await page.getByRole('dialog',{name:'参加者',exact:true}).waitFor();assert.equal(await integratedBody.evaluate(el=>el.scrollTop),saved);await capture('integrated-participants-restored-600');await closeDialog();
await scenario('reward-issued');await page.getByRole('button',{name:'報酬',exact:true}).click();await page.getByRole('dialog',{name:'報酬',exact:true}).waitFor();await page.waitForFunction(()=>document.querySelectorAll('.raid-room-dialogs .spinner').length===0);await capture('integrated-reward-600-top');await page.locator('.raid-room-dialogs .canonical-dialog-body').evaluate(el=>el.scrollTop=el.scrollHeight);await capture('integrated-reward-600-bottom');await closeDialog();
for(const width of [375,390,430]){await page.setViewportSize({width,height:844});await scenario('member');await page.locator('.ui-hub-page-scroll').evaluate(el=>el.scrollTop=0);await capture(`integrated-member-${width}-top`);const m=await page.locator('.ui-hub-page-content').evaluate(el=>({client:el.clientWidth,scroll:el.scrollWidth}));assert.ok(m.scroll<=m.client+1);await page.locator('.ui-hub-page-scroll').evaluate(el=>el.scrollTop=el.scrollHeight);await capture(`integrated-member-${width}-bottom`);assert.ok(await hit(page.getByRole('button',{name:'出撃準備',exact:true})));report.push({width,m});}
assert.deepEqual(errors,[]);await writeFile(`${out}/browser-report.json`,JSON.stringify({report,errors,profileRoundtrip:'PASS',integratedBrowser:'PASS',modalCount:'PASS',closeHit:'PASS',headerClose44:'PASS',presentRoute:'PASS'},null,2));await browser.close();console.log('Integrated Raid browser PASS: 375/390/430x844 plus 390x600 profile roundtrip, rewards scroll/close/Present, 12 detail states and real Browser integration.');
