import {chromium} from '@playwright/test';
import {mkdir,writeFile,copyFile,readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const out='docs/development/evidence/raid-visual-20260909';await mkdir(out,{recursive:true});
const b=await chromium.launch();const p=await b.newPage({viewport:{width:390,height:844}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.route('**/*',route=>{const u=new URL(route.request().url());return ['localhost','127.0.0.1'].includes(u.hostname)||u.protocol==='data:'?route.continue():route.abort();});
await p.goto('http://localhost:3037/qa/raid-top');const results=[];
for(const height of [844,600]){await p.setViewportSize({width:390,height});for(const scenario of ['approved','multiple','empty','long-name','broken-image']){
 await p.getByLabel('Mockシナリオ',{exact:true}).selectOption(scenario);await p.getByTestId('raid-top').waitFor();await p.evaluate(()=>document.fonts.ready);await p.locator('.ui-hub-page-scroll').evaluate(e=>e.scrollTop=0);
 const metrics=await p.getByTestId('raid-top').evaluate(e=>({width:e.clientWidth,scroll:e.scrollWidth,cards:[...e.querySelectorAll('.raid-top__joined,.raid-top__rescue,.raid-top__target')].map(x=>({type:x.className,width:x.getBoundingClientRect().width,height:x.getBoundingClientRect().height})),buttons:[...e.querySelectorAll('button')].map(x=>({text:x.textContent,width:x.getBoundingClientRect().width,height:x.getBoundingClientRect().height})),targets:[...e.querySelectorAll('.raid-top__target')].map(x=>({x:x.getBoundingClientRect().x,y:x.getBoundingClientRect().y}))}));
 assert.ok(metrics.scroll<=metrics.width+1);assert.ok(metrics.buttons.every(x=>x.width>=44&&x.height>=44));assert.equal(metrics.targets.length,2);assert.equal(metrics.targets[0].y,metrics.targets[1].y);assert.ok(metrics.targets[1].x>metrics.targets[0].x);
 await p.screenshot({path:`${out}/${scenario}-${height}-top.png`});await p.locator('.ui-hub-page-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);await p.screenshot({path:`${out}/${scenario}-${height}-lower.png`});
 assert.ok(await p.getByRole('button',{name:/開催中のレイドを探す/}).evaluate(e=>{const r=e.getBoundingClientRect();return e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}));results.push({height,scenario,...metrics});
}}
await p.getByLabel('Mockシナリオ',{exact:true}).selectOption('approved');await p.getByTestId('raid-top').waitFor();
for(const [name,expected] of [['続きへ',/qa-top-joined-0/],['救援に向かう',/qa-top-rescue-0.*qa-rescue-reference-0/],['この敵に挑む',/^choose:RAID_/],['開催中のレイドを探す',/^browse$/]]){await p.getByRole('button',{name:new RegExp(name)}).first().click();assert.match(await p.getByTestId('last-navigation').textContent(),expected);await p.getByRole('button',{name:'戻る',exact:true}).click();}
await p.setViewportSize({width:390,height:1800});await p.addStyleTag({content:'.raid-top-qa,.raid-top-qa-product,.ui-hub-page,.ui-hub-page-scroll{height:auto!important;max-height:none!important;overflow:visible!important}.raid-top-qa-tools,.raid-top-qa-footer{display:none!important}'});await p.getByTestId('raid-top').screenshot({path:`${out}/implementation-full.png`});
await copyFile('C:/Users/KIYOSH~1/AppData/Local/Temp/codex-file-preview-tGoKcQ/72FED8A9-DD6B-49B2-A934-3415464F5924.jpeg',`${out}/approved-reference.jpeg`);
const ref=(await readFile(`${out}/approved-reference.jpeg`)).toString('base64'),impl=(await readFile(`${out}/implementation-full.png`)).toString('base64');
await p.setViewportSize({width:840,height:1200});await p.setContent(`<html lang="ja"><meta charset="utf-8"><style>body{margin:0;background:#e9edf1;color:#162130;font:15px sans-serif;padding:20px}main{display:flex;gap:20px}section{width:390px}h2{font-size:20px}p{font-size:13px;line-height:1.6}.ref{height:665px;overflow:hidden}.ref img{width:390px;transform:translateY(-98px)}img{display:block;width:100%}</style><h1>レイドトップ｜承認モックとローカル実装</h1><p>2参戦／1救援／日次2エリア。実装は正規素材＋明示QAデータ。人物名・HP・期限はモックから転記していません。<br>共通ヘッダー・フッターは比較対象外。左はモックのトップ領域、右は実装の全領域。</p><main><section><h2>承認モック（390px換算）</h2><div class="ref"><img src="data:image/jpeg;base64,${ref}"></div></section><section><h2>今回の実装（表示幅362px）</h2><img style="width:362px" src="data:image/png;base64,${impl}"></section></main></html>`);await p.screenshot({path:`${out}/comparison.png`,fullPage:true});assert.deepEqual(errors,[]);await writeFile(`${out}/verification.json`,JSON.stringify({scope:'local Mock presentation; external requests blocked',results,navigation:'4 entry callbacks PASS',errors},null,2));await b.close();console.log('PASS: 10 layout cases, 4 entry callbacks, no external requests');
