import test from 'node:test';
import assert from 'node:assert/strict';
import {readRaidRoomPending,saveRaidRoomPending,clearRaidRoomPending,raidRoomPendingKey} from '../../src/domain/raidRoomBattlePending.ts';
import {createRaidRoomBattleAttempt} from '../../src/domain/raidRoomBattleAttempt.ts';
const payload={p_room_id:'room',p_request_id:'request',p_character_ids:['a','b'],p_tactic:'BALANCED'};
function storage(){const data=new Map();return {getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};}
const receipt={room_id:'room',replay_session_id:'replay',player_snapshot:[{id:'a'}],enemy_snapshot:[{},{},{},{},{}]};
test('pending保存はuser別・固定入力のみ、別userから見えない',()=>{const s=storage();saveRaidRoomPending('u1',payload,s);assert.equal(readRaidRoomPending('u2',s),null);assert.deepEqual(readRaidRoomPending('u1',s),{version:1,userId:'u1',payload});assert.deepEqual(Object.keys(JSON.parse(s.getItem(raidRoomPendingKey('u1')))).sort(),['payload','userId','version']);});
test('既存pendingを別request/別編成で上書きせず同入力のみ再保存',()=>{const s=storage();saveRaidRoomPending('u',payload,s);for(const p of [{...payload,p_request_id:'new'},{...payload,p_character_ids:['b','a']}])assert.throws(()=>saveRaidRoomPending('u',p,s));saveRaidRoomPending('u',payload,s);assert.deepEqual(readRaidRoomPending('u',s).payload,payload);});
test('clearは同user同requestだけ削除する',()=>{const s=storage();saveRaidRoomPending('u',payload,s);saveRaidRoomPending('v',payload,s);clearRaidRoomPending('u','different',s);assert.ok(readRaidRoomPending('u',s));clearRaidRoomPending('u','request',s);assert.equal(readRaidRoomPending('u',s),null);assert.ok(readRaidRoomPending('v',s));});
test('破損・異なるuser・重複編成pendingを拒否する',()=>{const s=storage();for(const raw of ['{',JSON.stringify({version:1,userId:'v',payload}),JSON.stringify({version:1,userId:'u',payload:{...payload,p_character_ids:['a','a']}})]){s.setItem(raidRoomPendingKey('u'),raw);assert.throws(()=>readRaidRoomPending('u',s));}});
test('保存write拒否またはreadback不一致ならstart RPCゼロ',async()=>{for(const s of [{getItem:()=>null,setItem(){throw Error('quota')},removeItem(){}},{getItem:()=>null,setItem(){},removeItem(){}}]){let count=0;const a=createRaidRoomBattleAttempt('room','request',{beforeSend:p=>saveRaidRoomPending('u',p,s)});await assert.rejects(()=>a.start({rpc(){count++;return {data:receipt,error:null}}},['a'],'BALANCED'));assert.equal(count,0);}});
test('復帰は本人receiptを先に読んで保存Replay使用、開始RPCゼロ',async()=>{const calls=[],a=createRaidRoomBattleAttempt('room','request',{initialPayload:payload});const r=await a.recover({rpc(n,p){calls.push([n,p]);return {data:receipt,error:null}}});assert.deepEqual(r.data,receipt);assert.deepEqual(calls,[['get_raid_room_battle_start_receipt_v1',{p_request_id:'request'}]]);});
test('receipt未存在だけ元payloadを再送し現在編成に置き換えない',async()=>{const calls=[],a=createRaidRoomBattleAttempt('room','request',{initialPayload:payload});const r=await a.recover({rpc(n,p){calls.push([n,p]);return {data:n.startsWith('get_')?null:receipt,error:null}}});assert.equal(r.data.replay_session_id,'replay');assert.equal(calls.length,2);assert.deepEqual(calls[1],['start_raid_room_battle_v1',payload]);});
test('receipt参照エラー・壊れた応答では開始再送しない',async()=>{for(const response of [{data:null,error:{message:'offline'}},{data:{},error:null}]){const calls=[],a=createRaidRoomBattleAttempt('room','request',{initialPayload:payload});assert.ok((await a.recover({rpc(n){calls.push(n);return response}})).error);assert.equal(calls.length,1);}});
