import React,{useState} from 'react';
import test,{afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {render,cleanup,fireEvent,waitFor} from '@testing-library/react';
import RaidRoomDetail from '../../src/app/components/raid/RaidRoomDetail';
import RaidRoomDialogs from '../../src/app/components/raid/RaidRoomDialogs';
import RaidRoomClearRewardPanel from '../../src/app/components/raid/RaidRoomClearRewardPanel';
import RaidRoomRescueRewardPanel from '../../src/app/components/raid/RaidRoomRescueRewardPanel';
import PublicUserProfile from '../../src/app/components/profile/PublicUserProfile';
import {createDetailFixture,success,type DetailScenario} from '../../src/app/qa/raid-detail/detailFixture';
afterEach(cleanup);
function mount(scenario:DetailScenario){const f=createDetailFixture(scenario,Date.now());const calls:string[]=[];const view=render(<RaidRoomDetail {...f} rescue={undefined} now={Date.now()} busy={false} onParticipants={()=>calls.push('participants')} onRewards={()=>calls.push('rewards')} onEnemyInfo={()=>calls.push('enemy')} action={<button>既存アクション</button>}/>);return {view,calls,f};}
for(const [scenario,label] of [['owner','主催者'],['member','通常参加'],['rescue','救援参加'],['not_joined','未参加']] as const)test(`${scenario}は既知のroleを表示し参加者権限を維持`,async()=>{const h=mount(scenario);await h.view.findByTestId('raid-room-detail');assert.ok(h.view.getAllByText(label).length);const button=h.view.getByRole('button',{name:'参加者一覧'});assert.equal(button.hasAttribute('disabled'),scenario==='not_joined');if(scenario!=='not_joined'){fireEvent.click(button);assert.deepEqual(h.calls,['participants']);}assert.doesNotMatch(h.view.container.textContent||'',/オンライン|楽勝|討伐困難/);});
for(const scenario of ['cleared','expired','error','unknown','no-guild'] as const)test(`${scenario}を0/成功に置換しない`,async()=>{const h=mount(scenario);await h.view.findByTestId('raid-room-detail');if(scenario==='unknown')assert.ok(h.view.getAllByText('未確認').length);if(scenario==='error')assert.ok(h.view.getAllByRole('alert').length);if(scenario==='no-guild')assert.ok(h.view.getByText('Guild未所属'));});
test('読込中は文字なしspinner',async()=>{const h=mount('loading');assert.ok(h.view.getByRole('status'));assert.equal(h.view.container.textContent,'');});
function ProfileRoundtrip(){const [f]=useState(()=>createDetailFixture('many',Date.now()));const [profile,setProfile]=useState<string|null>(null);return <><RaidRoomDialogs kind="participants" roomId={f.room.roomId} currentUserId={f.currentUserId} ownerUserId="qa-person-0" participants={f.participants} onClose={()=>{}} onRefresh={()=>{}} onOpenProfile={async id=>{setProfile(id);}} profileOpen={!!profile} rewards={success([])}/>{profile&&<PublicUserProfile profile={{id:profile,status:'ready',username:profile,level:30}} onClose={()=>setProfile(null)} onRetry={()=>{}}/>}</>;}
test('実プロフィールを開く間一覧を重ねず閉じると同一人/scroll位置へ復元',async()=>{const view=render(<ProfileRoundtrip/>);const body=document.querySelector<HTMLElement>('.raid-room-dialogs .canonical-dialog-body')!;body.scrollTop=480;fireEvent.click(view.getByRole('button',{name:'確認用参加者10のプロフィール'}));await waitFor(()=>assert.equal(document.querySelectorAll('.raid-room-dialogs').length,0));assert.equal(view.getAllByRole('dialog').length,1);fireEvent.click(view.getAllByRole('button',{name:'閉じる'}).at(-1)!);await waitFor(()=>assert.equal(document.querySelector<HTMLElement>('.raid-room-dialogs .canonical-dialog-body')?.scrollTop,480));assert.equal(view.getAllByRole('dialog').length,1);assert.equal((document.activeElement as HTMLElement).dataset.profileUser,'qa-person-9');});
test('プロフィール失敗は一覧に戻り再試行可能',async()=>{const f=createDetailFixture('many',Date.now());const view=render(<RaidRoomDialogs kind="participants" roomId={f.room.roomId} currentUserId={f.currentUserId} participants={f.participants} onClose={()=>{}} onRefresh={()=>{}} onOpenProfile={async()=>{throw Error('offline');}} rewards={success([])}/>);fireEvent.click(view.getByRole('button',{name:'確認用参加者2のプロフィール'}));await view.findByRole('alert');assert.equal(view.getAllByRole('dialog').length,1);assert.ok(view.getByRole('button',{name:'確認用参加者2のプロフィール'}));});
for(const scenario of ['reward-unconfigured','reward-planned','reward-issued'] as const)test(`${scenario}: 報酬予定と発行済みを区別`,async()=>{const f=createDetailFixture(scenario,Date.now());const clearClient={getReward:async()=>f.clear};const rescueClient={getReward:async()=>f.rescue};const view=render(<><RaidRoomClearRewardPanel client={clearClient} roomId={f.room.roomId} userId={f.currentUserId} plan={f.plan} onOpenPresents={()=>{}}/><RaidRoomRescueRewardPanel client={rescueClient} roomId={f.room.roomId} plan={f.plan} onOpenPresents={()=>{}}/></>);await waitFor(()=>assert.equal(view.container.querySelectorAll('.spinner').length,0));assert.equal(view.getAllByRole('region',{name:'報酬の予定内容'}).length,2);assert.equal(view.queryAllByRole('region',{name:'発行済みの報酬'}).length,scenario==='reward-issued'?2:0);if(scenario==='reward-issued'){assert.ok(view.getAllByText('受取済み').length);assert.ok(view.getAllByText('未受取').length);}else assert.equal(view.queryAllByText('受取済み').length,0);});



test('実PG display出力を表示parserへ通し予定へのPresent/別room混入を拒否',async()=>{
 const {readFileSync}=await import('node:fs');const {getRaidRoomDisplay}=await import('../../src/domain/raidRoomDisplayClient');
 const actual=JSON.parse(readFileSync('outputs/raid-detail/actual-display.json','utf8'));const calls:unknown[]=[];
 const result=await getRaidRoomDisplay({rpc:async(...args)=>{calls.push(args);return {data:actual,error:null};}},actual.roomId);assert.equal(result.membership,'rescue');assert.equal(result.clearPlan.status,'configured');assert.deepEqual(calls,[['get_raid_room_display_v1',{p_room_id:actual.roomId}]]);
 const bad=structuredClone(actual);bad.clearPlan.items[0].presentId='must-not-be-in-plan';await assert.rejects(()=>getRaidRoomDisplay({rpc:async()=>({data:bad,error:null})},actual.roomId));await assert.rejects(()=>getRaidRoomDisplay({rpc:async()=>({data:actual,error:null})},'different-room'));
});
