import test,{afterEach,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {renderHook,act,cleanup} from '@testing-library/react';
import {useBattle} from '../../src/hooks/useBattle';
beforeEach(()=>window.localStorage.clear());
afterEach(cleanup);
const noop=()=>{};
const unit=(id:string)=>({id,characterId:'c',name:'検証',stats:{hp:1000,atk:100,def:100,spd:100,luk:1},skills:[]});
const briefing:any={roomId:'room',raidBossInstanceId:'instance',raidVariantId:'BOSS_A',bossName:'ボス',membershipStatus:'joined',battleStartEnabled:true};
function setup(failures=0,throws=0,userId='user',readReceipt:any=null,existingSession:any=null,currentAttempt:any={data:{raidPoints:3,firstEntryFree:false},error:null}){
 const calls:any[]=[],errors:any[]=[];
 const receipt={room_id:'room',replay_session_id:'replay',player_snapshot:[unit('p')],enemy_snapshot:Array.from({length:5},(_,i)=>unit('e'+i)),cost:1,remaining_raid_points:4};
 (globalThis as any).__raidClient={
  async rpc(name:string,args:any){calls.push([name,args]);if(name==='get_current_raid_attempt_state'){if(currentAttempt instanceof Error)throw currentAttempt;return currentAttempt;}if(name==='start_raid_room_battle_v1' && throws-->0)throw Error('transport');const data:any=name==='acknowledge_raid_room_battle_recovery_v1'?{status:'acknowledged',requestId:args.p_request_id}:name==='get_raid_room_battle_start_receipt_v1'?readReceipt:name==='get_raid_room_briefing_v1'?briefing:name==='get_raid_room_v1'?{hp:{value:{current:1000}}}:name==='get_active_raids'?[{id:'instance',bossMasterId:'BOSS_A',currentHp:1000}]:name==='get_current_main_formation'?{characters:[{character_id:'c'}]}:name.startsWith('start_raid')?receipt:[];return {data,error:null};},
  from(name:string){const chain:any={select(){return chain},eq(){return chain},in(){return chain},insert(payload:any){calls.push(['insert:'+name,payload]);return chain},update(){return chain},single:async()=>({data:{id:'session'},error:null}),maybeSingle:async()=>({data:name==='battle_sessions'?existingSession:{id:'BOSS_A',boss_name:'ボス',max_hp:1000,skills:[]},error:null}),then(resolve:any){return Promise.resolve({data:[],error:null}).then(resolve)}};return chain;},
  functions:{async invoke(name:string,args:any){calls.push([name,args]);if(failures-->0)return {data:null,error:{message:'transient'}};return {data:{roomId:'room',winner:'ENEMY',events:[{index:0,round:1,type:'RESULT',payload:{winner:'ENEMY'}}],rawDamage:100,appliedDamage:100,personalContribution:100},error:null};}}
 };
 const options:any={session:{user:{id:userId}},userCharactersDbList:[{id:'owned',character_id:'c',level:1}],userEquipmentsList:[],userSkillsList:[],skillLimitBreakMaster:[],selectedMembers:['c'],selectedLeader:'c',userGuild:null,userGuildMember:null,gvgBaseControls:[],currentBaseId:'x',username:'検証',playCyberSe:noop,syncBootstrapData:async()=>{},pvpPoints:5,setPvpPoints:noop,userLevel:5,setUserLevel:noop,userXp:0,setUserXp:noop,vitality:100,setVitality:noop,pvpRate:1000,pvpRankings:[],raidBossHp:1000,raidBossMaxHp:1000,raidTotalDamage:0,setRaidTotalDamage:noop,setRaidPoints:(value:any)=>calls.push(['setRaidPoints',value]),setRaidFirstEntryFree:(value:any)=>calls.push(['setRaidFirstEntryFree',value]),requestRaidTopRefresh:noop,setConfirmDialogConfig:(x:any)=>calls.push(['dialog',x]),setErrorMessage:(x:any)=>errors.push(x),addGuildXpAndContributionByAction:async()=>{}};
 return {hook:renderHook(()=>useBattle(options)),calls,errors,receipt,options,remount:()=>renderHook(()=>useBattle(options))};
}
const count=(calls:any[],name:string)=>calls.filter(c=>c[0]===name).length;
test('実useBattle Room準備キャンセルでstart/resolveなし',async()=>{const {hook,calls,errors}=setup();await act(async()=>{await hook.result.current.prepareRaidRoomBattle(briefing)});assert.equal(hook.result.current.battleState,'SETUP',JSON.stringify(errors));act(()=>{assert.equal(hook.result.current.cancelPreparedRaidBattle(),true)});assert.equal(hook.result.current.battleState,null);assert.equal(count(calls,'start_raid_room_battle_v1'),0);assert.equal(count(calls,'resolve-battle'),0);});
test('実useBattle RoomconfirmはRoom start/resolve、旧開始/報酬なし',async()=>{const {hook,calls,errors}=setup();await act(async()=>{await hook.result.current.prepareRaidRoomBattle(briefing)});let ok;await act(async()=>{ok=await hook.result.current.confirmPreparedRaidBattle()});assert.equal(ok,true,JSON.stringify(errors));assert.equal(count(calls,'start_raid_room_battle_v1'),1);assert.equal(count(calls,'resolve-battle'),1);assert.equal(count(calls,'start_raid_battle'),0);assert.equal(count(calls,'get_current_raid_battle_rewards'),0);});
test('実useBattle resolve失敗後は同Replay再試行、再開始なし',async()=>{const {hook,calls,errors}=setup(2);await act(async()=>{await hook.result.current.prepareRaidRoomBattle(briefing)});let ok;await act(async()=>{ok=await hook.result.current.confirmPreparedRaidBattle()});assert.equal(ok,false);await act(async()=>{ok=await hook.result.current.confirmPreparedRaidBattle()});assert.equal(ok,true,JSON.stringify(errors));assert.equal(count(calls,'start_raid_room_battle_v1'),1);assert.equal(count(calls,'resolve-battle'),3);assert.deepEqual([...new Set(calls.filter(c=>c[0]==='resolve-battle').map(c=>c[1].body.replaySessionId))],['replay']);});
test('実useBattle 非Roomは旧開始と旧報酬参照を維持',async()=>{const {hook,calls,errors}=setup();await act(async()=>{await hook.result.current.startCardBattle('RAID','ボス','instance')});assert.equal(count(calls,'start_raid_battle'),0,'prepare must not start');let ok;await act(async()=>{ok=await hook.result.current.confirmPreparedRaidBattle()});assert.equal(ok,true,JSON.stringify(errors));assert.equal(count(calls,'start_raid_battle'),1,'old start');assert.equal(count(calls,'start_raid_room_battle_v1'),0);assert.ok(count(calls,'get_current_raid_battle_rewards')>=1,'old rewards');});

test('実useBattle 開始throwは互換sessionを保存せず同request再試行',async()=>{const {hook,calls}=setup(0,1);await act(async()=>{await hook.result.current.prepareRaidRoomBattle(briefing)});let ok;await act(async()=>{ok=await hook.result.current.confirmPreparedRaidBattle()});assert.equal(ok,false);assert.equal(count(calls,'insert:battle_sessions'),0);assert.equal(count(calls,'resolve-battle'),0);await act(async()=>{ok=await hook.result.current.confirmPreparedRaidBattle()});assert.equal(ok,true);const starts=calls.filter(c=>c[0]==='start_raid_room_battle_v1');assert.equal(starts.length,2);assert.deepEqual(starts[0][1],starts[1][1]);assert.equal(count(calls,'insert:battle_sessions'),1);});

test('実useBattle reload後はreceiptを読むだけで同Replay確定し追加開始なし',async()=>{const first=setup(2);await act(async()=>{await first.hook.result.current.prepareRaidRoomBattle(briefing)});await act(async()=>{await first.hook.result.current.confirmPreparedRaidBattle()});assert.equal(count(first.calls,'start_raid_room_battle_v1'),1);first.hook.unmount();const second=setup(0,0,'user',first.receipt);await act(async()=>{assert.equal(await second.hook.result.current.resumePendingRaidRoomBattle(),true)});assert.equal(count(second.calls,'get_raid_room_battle_start_receipt_v1'),1,JSON.stringify(second.errors));assert.equal(count(second.calls,'start_raid_room_battle_v1'),0);assert.equal(count(second.calls,'resolve-battle'),1);assert.equal(second.calls.find(c=>c[0]==='resolve-battle')[1].body.replaySessionId,'replay');assert.equal(window.localStorage.length,0);assert.deepEqual(second.calls.filter(c=>c[0]==='setRaidPoints'),[['setRaidPoints',3]],'current RPC value replaces old receipt RP 4');assert.deepEqual(second.calls.filter(c=>c[0]==='setRaidFirstEntryFree'),[['setRaidFirstEntryFree',false]]);const prev=second.hook.result.current.battleState;await act(async()=>{assert.equal(await second.hook.result.current.resumeActiveBattleSession('quest'),true)});assert.equal(second.hook.result.current.battleState,prev);assert.equal(count(second.calls,'resolve-battle'),1);});
test('実useBattle 開始通信不明reloadは同request同編成で再送する',async()=>{const first=setup(0,1);await act(async()=>{await first.hook.result.current.prepareRaidRoomBattle(briefing)});await act(async()=>{await first.hook.result.current.confirmPreparedRaidBattle()});const request=first.calls.find(c=>c[0]==='start_raid_room_battle_v1')[1];first.hook.unmount();const second=setup();second.options.selectedMembers=['changed'];second.options.userCharactersDbList=[];await act(async()=>{await second.hook.result.current.resumePendingRaidRoomBattle()});assert.deepEqual(second.calls.find(c=>c[0]==='start_raid_room_battle_v1')?.[1],request,JSON.stringify(second.errors));assert.equal(count(second.calls,'resolve-battle'),1);});
test('実useBattle 保存不可は開始/確定/互換sessionを送信しない',async()=>{const {hook,calls}=setup();await act(async()=>{await hook.result.current.prepareRaidRoomBattle(briefing)});const proto=Object.getPrototypeOf(window.localStorage),original=proto.setItem;proto.setItem=()=>{throw Error('quota')};try{await act(async()=>{await hook.result.current.confirmPreparedRaidBattle()})}finally{proto.setItem=original}assert.equal(count(calls,'start_raid_room_battle_v1'),0);assert.equal(count(calls,'resolve-battle'),0);assert.equal(count(calls,'insert:battle_sessions'),0);});
test('実useBattle 別userのpendingは復帰しない',async()=>{const first=setup(0,1);await act(async()=>{await first.hook.result.current.prepareRaidRoomBattle(briefing)});await act(async()=>{await first.hook.result.current.confirmPreparedRaidBattle()});first.hook.unmount();const second=setup(0,0,'other');await act(async()=>{assert.equal(await second.hook.result.current.resumePendingRaidRoomBattle(),false)});assert.equal(second.calls.length,0);assert.equal(window.localStorage.length,1);});
test('実useBattle 同時復帰呼出しはreceipt/resolve各1回',async()=>{const first=setup(0,1);await act(async()=>{await first.hook.result.current.prepareRaidRoomBattle(briefing)});await act(async()=>{await first.hook.result.current.confirmPreparedRaidBattle()});first.hook.unmount();const second=setup(0,0,'user',first.receipt);await act(async()=>{await Promise.all([second.hook.result.current.resumePendingRaidRoomBattle(),second.hook.result.current.resumePendingRaidRoomBattle()])});assert.equal(count(second.calls,'get_raid_room_battle_start_receipt_v1'),1);assert.equal(count(second.calls,'resolve-battle'),1);});
test('実useBattle receipt待機中にuser変更しても旧user応答を確定へ流さない',async()=>{
 const first=setup(0,1);await act(async()=>{await first.hook.result.current.prepareRaidRoomBattle(briefing)});await act(async()=>{await first.hook.result.current.confirmPreparedRaidBattle()});first.hook.unmount();
 const second=setup(0,0,'user',first.receipt),client=(globalThis as any).__raidClient,original=client.rpc;let release:any;client.rpc=(n:string,p:any)=>n==='get_raid_room_battle_start_receipt_v1'?new Promise(resolve=>{second.calls.push([n,p]);release=()=>resolve({data:first.receipt,error:null})}):original(n,p);
 let pending:any;act(()=>{pending=second.hook.result.current.resumePendingRaidRoomBattle()});second.options.session={user:{id:'other'}};second.hook.rerender();await act(async()=>{release();await pending});assert.equal(count(second.calls,'resolve-battle'),0);assert.equal(count(second.calls,'start_raid_room_battle_v1'),0);assert.equal(count(second.calls,'get_raid_room_briefing_v1'),0);assert.equal(window.localStorage.length,1);
});

test('実useBattle 互換session保存後clear前reloadは既存sessionを再利用',async()=>{const first=setup(2);await act(async()=>{await first.hook.result.current.prepareRaidRoomBattle(briefing)});await act(async()=>{await first.hook.result.current.confirmPreparedRaidBattle()});first.hook.unmount();const second=setup(0,0,'user',first.receipt,{id:'existing'});await act(async()=>{await second.hook.result.current.resumePendingRaidRoomBattle()});assert.equal(count(second.calls,'resolve-battle'),1);assert.equal(count(second.calls,'insert:battle_sessions'),0,JSON.stringify(second.errors));assert.equal(window.localStorage.length,0);});

test('実useBattle 復帰後の現在RP参照失敗でも表示値保持・確定Replay再開始なし',async()=>{for(const failed of [{data:null,error:{message:'offline'}},Error('transport')]){window.localStorage.clear();const first=setup(2);await act(async()=>{await first.hook.result.current.prepareRaidRoomBattle(briefing)});await act(async()=>{await first.hook.result.current.confirmPreparedRaidBattle()});first.hook.unmount();const second=setup(0,0,'user',first.receipt,null,failed);await act(async()=>{await second.hook.result.current.resumePendingRaidRoomBattle()});assert.equal(count(second.calls,'get_current_raid_attempt_state'),1);assert.equal(count(second.calls,'setRaidPoints'),0);assert.equal(count(second.calls,'setRaidFirstEntryFree'),0);assert.equal(count(second.calls,'start_raid_room_battle_v1'),0);assert.equal(count(second.calls,'resolve-battle'),1);assert.equal(window.localStorage.length,0);second.hook.unmount();}});

test('実useBattle local消失はserver開始記録から同Replay復帰、startなし',async()=>{const x=setup();const client=(globalThis as any).__raidClient,original=client.rpc;client.rpc=(n:string,p:any)=>n==='list_raid_room_battle_recoveries_v1'?(x.calls.push([n,p]),Promise.resolve({data:[{requestId:'request',roomId:'room',payload:{p_room_id:'room',p_request_id:'request',p_character_ids:['c'],p_tactic:'BALANCED'},receipt:x.receipt}],error:null})):original(n,p);await act(async()=>{assert.equal(await x.hook.result.current.resumePendingRaidRoomBattle(true),true)});assert.equal(count(x.calls,'start_raid_room_battle_v1'),0);assert.equal(count(x.calls,'resolve-battle'),1);assert.equal(count(x.calls,'acknowledge_raid_room_battle_recovery_v1'),1);assert.equal(window.localStorage.length,0);});
test('実useBattle server一覧空は自動出撃せずflag false旧bootを維持',async()=>{const x=setup();await act(async()=>{assert.equal(await x.hook.result.current.resumePendingRaidRoomBattle(),false)});assert.equal(x.calls.length,0);await act(async()=>{assert.equal(await x.hook.result.current.resumePendingRaidRoomBattle(true),false)});assert.equal(count(x.calls,'list_raid_room_battle_recoveries_v1'),1);assert.equal(count(x.calls,'start_raid_room_battle_v1'),0);assert.equal(count(x.calls,'resolve-battle'),0);});
test('実useBattle ack失敗はlocal復帰情報を保持',async()=>{const x=setup(),client=(globalThis as any).__raidClient,original=client.rpc;client.rpc=(n:string,p:any)=>n==='acknowledge_raid_room_battle_recovery_v1'?Promise.resolve({data:null,error:{message:'offline'}}):original(n,p);await act(async()=>{await x.hook.result.current.prepareRaidRoomBattle(briefing)});await act(async()=>{await x.hook.result.current.confirmPreparedRaidBattle()});assert.equal(count(x.calls,'resolve-battle'),1);assert.equal(window.localStorage.length,1);});
test('実useBattle 取消通信失敗は保持して再試行、started復帰/cancelledのみ消去',async()=>{for(const status of ['started','cancelled']){window.localStorage.clear();const first=setup(0,1);await act(async()=>{await first.hook.result.current.prepareRaidRoomBattle(briefing)});await act(async()=>{await first.hook.result.current.confirmPreparedRaidBattle()});first.hook.unmount();const x=setup(),client=(globalThis as any).__raidClient,original=client.rpc;let cancelFailures=1;client.rpc=(n:string,p:any)=>n==='get_raid_room_battle_start_receipt_v1'?Promise.resolve({data:null,error:{message:'denied'}}):n==='cancel_raid_room_battle_request_v1'?(x.calls.push([n,p]),Promise.resolve(cancelFailures-->0?{data:null,error:{message:'offline'}}:{data:{status,receipt:x.receipt},error:null})):original(n,p);await act(async()=>{await x.hook.result.current.resumePendingRaidRoomBattle()});assert.equal(window.localStorage.length,1);const dialog=x.calls.filter(c=>c[0]==='dialog').at(-1)?.[1];assert.ok(dialog);await act(async()=>{await assert.rejects(()=>dialog.onConfirm(),/offline/)});assert.equal(window.localStorage.length,1);assert.equal(count(x.calls,'resolve-battle'),0);await act(async()=>{await dialog.onConfirm()});assert.equal(count(x.calls,'start_raid_room_battle_v1'),0);assert.equal(count(x.calls,'resolve-battle'),status==='started'?1:0);assert.equal(window.localStorage.length,0);x.hook.unmount();}});
