import test,{afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {renderHook,act,cleanup} from '@testing-library/react';
import {useBattle} from '../../src/hooks/useBattle';
afterEach(cleanup);
const noop=()=>{};
const unit=(id:string)=>({id,characterId:'c',name:'検証',stats:{hp:1000,atk:100,def:100,spd:100,luk:1},skills:[]});
const briefing:any={roomId:'room',raidBossInstanceId:'instance',raidVariantId:'BOSS_A',bossName:'ボス',membershipStatus:'joined',battleStartEnabled:true};
function setup(failures=0,throws=0){
 const calls:any[]=[],errors:any[]=[];
 const receipt={room_id:'room',replay_session_id:'replay',player_snapshot:[unit('p')],enemy_snapshot:Array.from({length:5},(_,i)=>unit('e'+i)),cost:1,remaining_raid_points:4};
 (globalThis as any).__raidClient={
  async rpc(name:string,args:any){calls.push([name,args]);if(name==='start_raid_room_battle_v1' && throws-->0)throw Error('transport');const data:any=name==='get_raid_room_briefing_v1'?briefing:name==='get_raid_room_v1'?{hp:{value:{current:1000}}}:name==='get_active_raids'?[{id:'instance',bossMasterId:'BOSS_A',currentHp:1000}]:name==='get_current_main_formation'?{characters:[{character_id:'c'}]}:name.startsWith('start_raid')?receipt:[];return {data,error:null};},
  from(name:string){const chain:any={select(){return chain},eq(){return chain},in(){return chain},insert(payload:any){calls.push(['insert:'+name,payload]);return chain},update(){return chain},single:async()=>({data:{id:'session'},error:null}),maybeSingle:async()=>({data:{id:'BOSS_A',boss_name:'ボス',max_hp:1000,skills:[]},error:null}),then(resolve:any){return Promise.resolve({data:[],error:null}).then(resolve)}};return chain;},
  functions:{async invoke(name:string,args:any){calls.push([name,args]);if(failures-->0)return {data:null,error:{message:'transient'}};return {data:{roomId:'room',winner:'ENEMY',events:[{index:0,round:1,type:'RESULT',payload:{winner:'ENEMY'}}],rawDamage:100,appliedDamage:100,personalContribution:100},error:null};}}
 };
 const options:any={session:{user:{id:'user'}},userCharactersDbList:[{id:'owned',character_id:'c',level:1}],userEquipmentsList:[],userSkillsList:[],skillLimitBreakMaster:[],selectedMembers:['c'],selectedLeader:'c',userGuild:null,userGuildMember:null,gvgBaseControls:[],currentBaseId:'x',username:'検証',playCyberSe:noop,syncBootstrapData:async()=>{},pvpPoints:5,setPvpPoints:noop,userLevel:5,setUserLevel:noop,userXp:0,setUserXp:noop,vitality:100,setVitality:noop,pvpRate:1000,pvpRankings:[],raidBossHp:1000,raidBossMaxHp:1000,raidTotalDamage:0,setRaidTotalDamage:noop,setRaidPoints:noop,setRaidFirstEntryFree:noop,requestRaidTopRefresh:noop,setErrorMessage:(x:any)=>errors.push(x),addGuildXpAndContributionByAction:async()=>{}};
 return {hook:renderHook(()=>useBattle(options)),calls,errors};
}
const count=(calls:any[],name:string)=>calls.filter(c=>c[0]===name).length;
test('実useBattle Room準備キャンセルでstart/resolveなし',async()=>{const {hook,calls,errors}=setup();await act(async()=>{await hook.result.current.prepareRaidRoomBattle(briefing)});assert.equal(hook.result.current.battleState,'SETUP',JSON.stringify(errors));act(()=>{assert.equal(hook.result.current.cancelPreparedRaidBattle(),true)});assert.equal(hook.result.current.battleState,null);assert.equal(count(calls,'start_raid_room_battle_v1'),0);assert.equal(count(calls,'resolve-battle'),0);});
test('実useBattle RoomconfirmはRoom start/resolve、旧開始/報酬なし',async()=>{const {hook,calls,errors}=setup();await act(async()=>{await hook.result.current.prepareRaidRoomBattle(briefing)});let ok;await act(async()=>{ok=await hook.result.current.confirmPreparedRaidBattle()});assert.equal(ok,true,JSON.stringify(errors));assert.equal(count(calls,'start_raid_room_battle_v1'),1);assert.equal(count(calls,'resolve-battle'),1);assert.equal(count(calls,'start_raid_battle'),0);assert.equal(count(calls,'get_current_raid_battle_rewards'),0);});
test('実useBattle resolve失敗後は同Replay再試行、再開始なし',async()=>{const {hook,calls,errors}=setup(2);await act(async()=>{await hook.result.current.prepareRaidRoomBattle(briefing)});let ok;await act(async()=>{ok=await hook.result.current.confirmPreparedRaidBattle()});assert.equal(ok,false);await act(async()=>{ok=await hook.result.current.confirmPreparedRaidBattle()});assert.equal(ok,true,JSON.stringify(errors));assert.equal(count(calls,'start_raid_room_battle_v1'),1);assert.equal(count(calls,'resolve-battle'),3);assert.deepEqual([...new Set(calls.filter(c=>c[0]==='resolve-battle').map(c=>c[1].body.replaySessionId))],['replay']);});
test('実useBattle 非Roomは旧開始と旧報酬参照を維持',async()=>{const {hook,calls,errors}=setup();await act(async()=>{await hook.result.current.startCardBattle('RAID','ボス','instance')});assert.equal(count(calls,'start_raid_battle'),0,'prepare must not start');let ok;await act(async()=>{ok=await hook.result.current.confirmPreparedRaidBattle()});assert.equal(ok,true,JSON.stringify(errors));assert.equal(count(calls,'start_raid_battle'),1,'old start');assert.equal(count(calls,'start_raid_room_battle_v1'),0);assert.ok(count(calls,'get_current_raid_battle_rewards')>=1,'old rewards');});

test('実useBattle 開始throwは互換sessionを保存せず同request再試行',async()=>{const {hook,calls}=setup(0,1);await act(async()=>{await hook.result.current.prepareRaidRoomBattle(briefing)});let ok;await act(async()=>{ok=await hook.result.current.confirmPreparedRaidBattle()});assert.equal(ok,false);assert.equal(count(calls,'insert:battle_sessions'),0);assert.equal(count(calls,'resolve-battle'),0);await act(async()=>{ok=await hook.result.current.confirmPreparedRaidBattle()});assert.equal(ok,true);const starts=calls.filter(c=>c[0]==='start_raid_room_battle_v1');assert.equal(starts.length,2);assert.deepEqual(starts[0][1],starts[1][1]);assert.equal(count(calls,'insert:battle_sessions'),1);});
