import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {billingConfig,verifyStripeEvent,validateSession,uuid} from '../../src/server/billing/contracts.ts';
const config={BILLING_SANDBOX_ENABLED:'true',VERCEL_ENV:'preview',NEXT_PUBLIC_SUPABASE_URL:'https://sufvuqdnqohpfzkwxohq.supabase.co',STRIPE_SECRET_KEY:'sk_test_fixture',STRIPE_WEBHOOK_SECRET:'whsec_fixture',SUPABASE_SERVICE_ROLE_KEY:'fixture',BILLING_RETURN_ORIGIN:'https://preview.example.com'};
assert.equal(billingConfig(config).origin,'https://preview.example.com');
for(const patch of [{VERCEL_ENV:'production'},{NEXT_PUBLIC_SUPABASE_URL:'https://ktpolnkyyfkowxdmijww.supabase.co'},{STRIPE_SECRET_KEY:'sk_live_fixture'},{BILLING_SANDBOX_ENABLED:'false'},{BILLING_RETURN_ORIGIN:'https://www.tribe-neon.com'},{BILLING_RETURN_ORIGIN:'http://preview.example.com'},{SUPABASE_SERVICE_ROLE_KEY:''}]) assert.throws(()=>billingConfig({...config,...patch}));
const now=Date.now(),t=String(Math.floor(now/1000)),raw=JSON.stringify({id:'evt_fixture',livemode:false});
const sig=createHmac('sha256','whsec_fixture').update(`${t}.${raw}`).digest('hex');
assert.equal(verifyStripeEvent(raw,`t=${t},v1=${sig}`,'whsec_fixture',now).id,'evt_fixture');
assert.throws(()=>verifyStripeEvent(raw+' ',`t=${t},v1=${sig}`,'whsec_fixture',now));
assert.throws(()=>verifyStripeEvent(raw,`t=${t},v1=${sig}`,'whsec_wrong',now));
assert.throws(()=>verifyStripeEvent(raw,`t=${t},v1=${sig}`,'whsec_fixture',now+301000));
assert.equal(verifyStripeEvent(raw,`t=${t},v1=${'0'.repeat(64)},v1=${sig}`,'whsec_fixture',now).id,'evt_fixture');
const order={id:'order1',user_id:'user1',product_id:'diamond_300',amount_jpy:300,stripe_session_id:null};
const session={id:'cs_test_fixture',livemode:false,status:'complete',payment_status:'paid',amount_total:300,currency:'jpy',client_reference_id:'order1',metadata:{order_id:'order1',user_id:'user1',product_id:'diamond_300'}};
assert.equal(validateSession(session,order),true);
assert.equal(validateSession({...session,status:'open',payment_status:'unpaid'},order),false);
for(const patch of [{livemode:true},{amount_total:1},{currency:'usd'},{client_reference_id:'other'},{id:'cs_live_fixture'},{metadata:{...session.metadata,user_id:'other'}}]) assert.throws(()=>validateSession({...session,...patch},order));
assert.throws(()=>validateSession(session,{...order,stripe_session_id:'cs_test_other'}));
assert.throws(()=>uuid('../other-user'));
console.log('PASS: sandbox境界7種、署名改ざん/秘密鍵/時刻/複数署名、金額/通貨/注文/所有者/session照合、未決済判定');
