import assert from 'node:assert/strict';
import { reconcileCheckout, terminalOrderResult } from '../../src/server/billing/reconciliation.ts';
import { validateSession } from '../../src/server/billing/contracts.ts';
import { catalogMatches, PAID_PACKS } from '../../src/server/billing/catalog.ts';
const original={id:'order1',user_id:'user1',product_id:'beginner_pack_01',amount_jpy:100,status:'PENDING',stripe_session_id:'cs_test_first'};
const session={id:'cs_test_first',livemode:false,status:'expired',payment_status:'unpaid',amount_total:100,currency:'jpy',client_reference_id:'order1',metadata:{order_id:'order1',user_id:'user1',product_id:'beginner_pack_01'}};
let latest={...original}; const calls=[];
const deps={validate:validateSession,order:async()=>latest,rpc:async(name)=>{calls.push(name);latest={...latest,status:name==='billing_grant_order'?'GRANTED':'EXPIRED'};return {status:latest.status};}};
assert.equal((await reconcileCheckout(session,deps)).status,'EXPIRED');
assert.equal(terminalOrderResult(latest).status,'EXPIRED');
latest={...original};calls.length=0;
// expire更新直前に別workerが配送を確定したケース。
const concurrent={...deps,rpc:async(name)=>{calls.push(name);latest={...original,status:'GRANTED'};return {order_id:original.id};}};
assert.equal((await reconcileCheckout(session,concurrent,original)).status,'GRANTED');
assert.deepEqual(calls,['billing_expire_order']);
calls.length=0;
assert.equal((await reconcileCheckout(session,deps)).status,'GRANTED');
assert.deepEqual(calls,[]);
latest={...original,status:'GRANTED'};
assert.equal((await reconcileCheckout({...session,status:'open'},deps,original)).status,'GRANTED');
latest={...original};calls.length=0;
assert.equal((await reconcileCheckout({...session,status:'complete',payment_status:'paid'},deps)).status,'GRANTED');
assert.deepEqual(calls,['billing_grant_order']);
await assert.rejects(()=>reconcileCheckout({...session,amount_total:1},deps),/一致/);
const catalog=PAID_PACKS.map(pack=>({...pack,validity_days:120,items:Object.entries(pack.items).map(([itemId,quantity])=>({itemId,quantity}))}));
assert.equal(catalogMatches(catalog),true);
assert.equal(catalogMatches(catalog.map((p,i)=>i? p:{...p,validity_days:undefined})),false);
assert.equal(catalogMatches(catalog.map((p,i)=>i? p:{...p,items:p.items.map((item,j)=>j?item:{...item,quantity:5000})})),false);
console.log('PASS: 配送/期限競合・古い未決済イベント・支払済のみ付与・価格不一致・旧商品catalog拒否');
