import assert from 'node:assert/strict';
import fs from 'node:fs';
const modulePath=process.env.PGLITE_MODULE || '@electric-sql/pglite';
const {PGlite}=await import(modulePath);
const db=new PGlite();
await db.exec(`create role authenticated; create role anon; create schema auth;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create table public.users(id uuid primary key,level int,cash bigint,guild_id uuid);
create table public.guilds(id uuid primary key default gen_random_uuid(),name text,leader_id uuid,level int,xp bigint,funds bigint,recruitment_mode text,approval_required boolean,is_disbanded boolean not null default false,logo_icon text,equipped_decoration text,equipped_banner text);
create table public.guild_members(guild_id uuid references guilds,user_id uuid,role text,weekly_contribution int,total_contribution int,primary key(guild_id,user_id));
create table public.guild_join_requests(user_id uuid,status text,reviewed_at timestamptz,reviewed_by uuid);
create function public.evaluate_mission_progress(uuid,text,integer) returns void language sql as $$ select $$;
create table public.cosmetic_master(id text primary key,owner_scope text not null check(owner_scope in ('USER','CHARACTER','GUILD')),slot text not null,rarity text not null default 'COMMON',display_name text not null,asset_key text,preview_key text,source_type text not null default 'SYSTEM',source_reference text,expires_enabled boolean not null default false,metadata jsonb not null default '{}',active boolean not null default true,created_at timestamptz not null default now());
create table public.guild_cosmetics(guild_id uuid,cosmetic_id text,expires_at timestamptz,primary key(guild_id,cosmetic_id));
create table public.guild_equipped_cosmetics(guild_id uuid references guilds,slot text,cosmetic_id text references cosmetic_master,equipped_at timestamptz default now(),primary key(guild_id,slot));`);
const existing=fs.readFileSync('supabase/migrations/20260830000210_canonical_master_freeze_runtime.sql','utf8');
await db.exec(existing.slice(existing.indexOf('create or replace function public.create_guild_v2'),existing.indexOf('-- Quest canonical')));
const file=fs.readdirSync('supabase/migrations').find(x=>x.endsWith('_guild_emblem_standard_identity.sql'));
await db.exec(fs.readFileSync('supabase/migrations/'+file,'utf8'));
const master='00000000-0000-0000-0000-000000000001', sub='00000000-0000-0000-0000-000000000002', member='00000000-0000-0000-0000-000000000003', outsider='00000000-0000-0000-0000-000000000004';
const scalar=async sql=>(await db.query(sql)).rows[0].v;
const auth=async id=>db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);
const deny=async sql=>{await assert.rejects(()=>db.query(sql));};
await db.exec(`insert into users(id,level,cash) values('${master}',5,1000);`);
await auth(master);
const created=await scalar(`select public.create_guild_v2('${master}','TEST',500) v`),g=created.guild_id;
assert.equal(await scalar(`select cash v from users where id='${master}'`),500);
assert.equal(await scalar(`select cosmetic_id v from guild_equipped_cosmetics where guild_id='${g}'`),'guild_standard_01');
assert.equal(await scalar(`select count(*)::int v from guild_cosmetics`),0);
await db.exec(`insert into guild_members(guild_id,user_id,role) values('${g}','${sub}','SUB_MASTER'),('${g}','${member}','MEMBER')`);
assert.equal((await scalar(`select list_guild_emblems('${g}') v`)).length,8);
await scalar(`select set_guild_emblem('${g}','guild_standard_02') v`);
await auth(sub); await scalar(`select set_guild_emblem('${g}','guild_standard_03') v`);
assert.equal((await scalar(`select get_guild_emblems(array['${g}'::uuid,'${g}'::uuid]) v`))[0].emblem_id,'guild_standard_03');
assert.equal(await scalar(`select logo_icon v from guilds where id='${g}'`),'/guild-emblems/guild_standard_03.svg');
for(const who of [member,outsider,'']){await auth(who);await deny(`select set_guild_emblem('${g}','guild_standard_04')`);await deny(`select equip_guild_cosmetic('${g}','GUILD_EMBLEM','guild_standard_04')`);}
await auth(master);
await db.exec(`delete from guild_equipped_cosmetics where guild_id='${g}' and slot='GUILD_EMBLEM'; update guilds set logo_icon='/legacy.svg' where id='${g}'`);
assert.equal((await scalar(`select get_guild_emblems(array['${g}'::uuid]) v`))[0].asset_path,'/legacy.svg');
await db.exec(`update guilds set logo_icon=null where id='${g}'`);
assert.equal((await scalar(`select get_guild_emblems(array['${g}'::uuid]) v`))[0].asset_path,'/guild-emblems/guild_standard_01.svg');
for(const id of ['missing']) await deny(`select set_guild_emblem('${g}','${id}')`);
await db.exec(`insert into cosmetic_master(id,owner_scope,slot,display_name,asset_key) values('limited','GUILD','GUILD_EMBLEM','限定','/limited.svg'),('background','GUILD','GUILD_BASE_BACKGROUND','背景','/bg.svg'); update cosmetic_master set active=false where id='guild_standard_08';`);
await deny(`select set_guild_emblem('${g}','guild_standard_08')`);
await deny(`select set_guild_emblem('${g}','limited')`);
await deny(`select set_guild_emblem('${g}','background')`);
await db.exec(`insert into guild_cosmetics values('${g}','limited',now()-interval '1 day'),('${g}','background',null);`);
await deny(`select set_guild_emblem('${g}','limited')`);
await db.exec(`update guild_cosmetics set expires_at=now()+interval '1 day' where cosmetic_id='limited'`);
await scalar(`select set_guild_emblem('${g}','limited') v`);
await db.exec(`update guild_cosmetics set expires_at=now()-interval '1 day' where cosmetic_id='limited'`);
assert.equal((await scalar(`select get_guild_emblems(array['${g}'::uuid]) v`))[0].asset_path,'/guild-emblems/guild_standard_01.svg');
await auth(sub);await deny(`select equip_guild_cosmetic('${g}','GUILD_BASE_BACKGROUND','background')`);
await auth(outsider);await deny(`select equip_guild_cosmetic('${g}','GUILD_BASE_BACKGROUND','background')`);
await auth(master);await scalar(`select equip_guild_cosmetic('${g}','GUILD_BASE_BACKGROUND','background') v`);
await db.exec(`delete from guild_members where user_id='${sub}'`);
assert.equal(await scalar(`select count(*)::int v from guild_cosmetics where guild_id='${g}'`),2);
await auth(sub);await deny(`select set_guild_emblem('${g}','guild_standard_01')`);await auth(master);
await db.exec(`update guilds set is_disbanded=true where id='${g}'`);await deny(`select set_guild_emblem('${g}','guild_standard_01')`);
assert.deepEqual(await scalar(`select get_guild_emblems(array['${g}'::uuid]) v`),[]);
assert.equal(await scalar(`select has_function_privilege('anon','public.set_guild_emblem(uuid,text)','execute') v`),false);
assert.equal(await scalar(`select has_function_privilege('authenticated','public.initialize_guild_emblem()','execute') v`),false);
console.log('PASS: create/default/no unlock rows; Master/Sub Master; member/nonmember/auth guards; old RPC bypass; active/owned/expiry; batch projection; legacy background permissions; disbanded; execute grants.');
await db.close();
