import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const root='docs/development/raid-production-release';const pat=fs.readFileSync(path.join(os.homedir(),'.supabase/access-token'),'utf8').trim();
const query=async sql=>{const r=await fetch('https://api.supabase.com/v1/projects/ktpolnkyyfkowxdmijww/database/query',{method:'POST',headers:{Authorization:`Bearer ${pat}`,'Content-Type':'application/json'},body:JSON.stringify({query:'begin read only;'+sql+';rollback;'})});assert.ok(r.ok);return r.json();};
const rows=await query(`select jsonb_build_object('functions',(select jsonb_agg(jsonb_build_object('name',proname,'args',pg_get_function_identity_arguments(oid),'hash',md5(pg_get_functiondef(oid)),'acl',proacl,'owner',pg_get_userbyid(proowner)) order by proname) from pg_proc where pronamespace='public'::regnamespace and prokind='f'),'profiles',(select jsonb_agg(profile order by raid_variant_id,difficulty_id) from raid_room_combat_profiles),'creation',(select to_jsonb(t) from raid_room_creation_settings t),'battle',(select to_jsonb(t) from raid_room_battle_settings t),'rescue',(select to_jsonb(t) from raid_room_rescue_settings t),'legacy',(select to_jsonb(t) from raid_legacy_settings t),'difficulty',(select jsonb_agg(to_jsonb(t) order by difficulty) from raid_room_difficulty_rules t),'clear',(select jsonb_agg(to_jsonb(t) order by difficulty) from raid_room_clear_reward_rules t),'rescueRules',(select jsonb_agg(to_jsonb(t) order by difficulty) from raid_room_rescue_reward_rules t),'clearItems',(select jsonb_agg(to_jsonb(t) order by difficulty,item_id) from raid_room_clear_reward_items t),'rescueItems',(select jsonb_agg(to_jsonb(t) order by difficulty,item_id) from raid_room_rescue_reward_items t),'cron',(select jsonb_agg(to_jsonb(j) order by jobid) from cron.job j),'cronLast',(select jsonb_agg(to_jsonb(d)) from (select status,return_message,start_time from cron.job_run_details where jobid=(select jobid from cron.job where jobname='raid-room-expiry-minute') order by start_time desc limit 1)d),'rooms',(select count(*) from raid_rooms),'bossHash',(select md5(jsonb_agg(to_jsonb(t) order by id)::text) from raid_bosses t)) state`);
const s=rows[0].state,before=JSON.parse(fs.readFileSync(root+'/catalog-before.json'))[0].audit;
const allowed=new Set(['01-snapshot-dependency.sql','02-raid-delta.sql','06-launch-balance.sql'].flatMap(f=>[...fs.readFileSync(root+'/bundle/'+f,'utf8').matchAll(/create\s+or\s+replace\s+function\s+public\.([a-z0-9_]+)/gi)].map(x=>x[1])));
let protectedCount=0;for(const f of before.functions.filter(x=>!allowed.has(x.name))){const a=s.functions.find(x=>x.name===f.name&&x.args===f.args);assert.ok(a,'Missing '+f.name);assert.equal(a.hash,f.md5,f.name);assert.deepEqual(a.acl,f.acl,f.name+' ACL');protectedCount++;}
const expected=JSON.parse(fs.readFileSync('config/raid-room/launch-balance.json')).profiles;assert.equal(s.profiles.length,28);for(const p of expected)assert.deepEqual(s.profiles.find(x=>x.raidVariantId===p.raidVariantId&&x.difficultyId===p.difficultyId),p);
const approved=JSON.parse(fs.readFileSync(root+'/approved-settings.json'));for(const p of approved.difficulties){const d=s.difficulty.find(x=>x.difficulty===p.id),c=s.clear.find(x=>x.difficulty===p.id);assert.equal(Number(d.rescue_min_battles),p.rescueMinimumBattles);assert.equal(Number(d.rescue_min_contribution_damage),p.rescueDamageInclusive);assert.equal(Number(c.minimum_contribution_damage),p.clearDamageExclusive);assert.ok(c.enabled);assert.ok(s.rescueRules.find(x=>x.difficulty===p.id).enabled);assert.deepEqual(s.clearItems.filter(x=>x.difficulty===p.id).map(x=>({itemId:x.item_id,quantity:x.quantity})),p.clearItems);assert.deepEqual(s.rescueItems.filter(x=>x.difficulty===p.id).map(x=>({itemId:x.item_id,quantity:x.quantity})),p.rescueItems);}
for(const j of before.cron){const a=s.cron.find(x=>x.jobid===j.jobid);for(const k of Object.keys(j))assert.deepEqual(a[k],j[k],'Cron '+j.jobname+' '+k);}
assert.equal(s.cronLast[0]?.status,'succeeded');
const report={at:new Date().toISOString(),status:'PASS',protectedFunctions:protectedCount,profiles:28,members:140,difficulty:s.difficulty,clear:s.clear,clearItems:s.clearItems,rescueItems:s.rescueItems,creation:s.creation,battle:s.battle,rescue:s.rescue,legacy:s.legacy,cronLast:s.cronLast,rooms:s.rooms,oldBossHashMatches:s.bossHash===JSON.parse(fs.readFileSync(root+'/db-applied.json')).pre[0].state.bossHash};
fs.writeFileSync(root+'/postflight-'+(s.creation.enabled?'open':'closed')+'.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
