// Production catalogを隔離PostgreSQLへ再構成。Native adapterはloopback専用。外部DBへ接続しない。
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
const sha=s=>createHash('sha256').update(s).digest('hex');
const modulePath=process.env.RAID_PGLITE_MODULE;
if(!modulePath) throw new Error('RAID_PGLITE_MODULEにPGlite 0.5.8のローカルentryを指定してください');
const {PGlite}=await import(pathToFileURL(path.resolve(modulePath)).href);
const db=new PGlite();
const dir='docs/development/raid-production-preparation/audit-a';
const c=JSON.parse(fs.readFileSync('docs/development/raid-production-release/catalog-before.json','utf8'))[0].audit;
const quote=s=>'"'+s.replaceAll('"','""')+'"';
const result={engine:process.env.RAID_REHEARSAL_ENGINE||'PGlite 0.5.8 / in-memory only',limitations:['空データから列・制約・関数・triggerを再構成。実ユーザーはコピーしない。','AuthはGUC参照stub。Cronは実行しない。複数接続・Edge・UI受入ではない。'],steps:[]};
try {
 if(process.env.RAID_REHEARSAL_ENGINE)await db.exec("do $$ begin if not exists(select from pg_roles where rolname='postgres') then create role postgres superuser; end if; end $$; set role postgres;");
 await db.exec(`do $$ begin if not exists(select from pg_roles where rolname='anon') then create role anon; end if; if not exists(select from pg_roles where rolname='authenticated') then create role authenticated; end if; if not exists(select from pg_roles where rolname='service_role') then create role service_role; end if; end $$;
 create schema auth; create table auth.users(id uuid primary key,created_at timestamptz default now(),is_anonymous boolean default true);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;
 create function auth.role() returns text language sql stable as $$select current_setting('request.jwt.claim.role',true)$$;
 set check_function_bodies=off;`);
 result.serverVersion=(await db.query('select version() value')).rows[0].value;
 const seqs=new Set(c.columns.flatMap(x=>[...(x.default??'').matchAll(/nextval\('([^']+)'/g)].map(m=>m[1])));
 for(const s of seqs) await db.exec(`create sequence ${s};`);
 for(const r of c.relations.filter(r=>r.kind!=='v')){
   const columns=c.columns.filter(x=>x.table===r.name);
   await db.exec(`create table public.${quote(r.name)} (${columns.map(x=>`${quote(x.column)} ${x.type}${x.identity?(x.identity==='a'?' generated always as identity':' generated by default as identity'):x.generated?` generated always as (${x.default}) stored`:x.default?` default ${x.default}`:''}${x.not_null?' not null':''}`).join(',')});`);
 }
 for(const f of c.functions.filter(f=>f.definition)) await db.exec(f.definition+';');
 for(const v of JSON.parse(fs.readFileSync(dir+'/views.json','utf8')))await db.exec('create view public.'+quote(v.name)+(v.options?.length?' with ('+v.options.join(',')+')':'')+' as '+v.definition);
 for(const con of c.constraints.filter(x=>!x.definition.startsWith('FOREIGN KEY'))) await db.exec(`alter table public.${quote(con.table)} add constraint ${quote(con.name)} ${con.definition};`);
 for(const con of c.constraints.filter(x=>x.definition.startsWith('FOREIGN KEY'))) await db.exec(`alter table public.${quote(con.table)} add constraint ${quote(con.name)} ${con.definition};`);
 for(const idx of c.indexes.filter(x=>!c.constraints.some(k=>k.name===x.indexname))) await db.exec(idx.indexdef+';');
 for(const t of c.triggers.filter(t=>c.functions.some(f=>f.definition&&t.function.split('(')[0].replace('public.','')===f.name))) await db.exec(t.definition+';');

 const privilege={a:'INSERT',r:'SELECT',w:'UPDATE',d:'DELETE',D:'TRUNCATE',x:'REFERENCES',t:'TRIGGER',m:'MAINTAIN',X:'EXECUTE'};
 const restoreAcl=async(target,acl)=>{if(!acl)return;await db.exec('revoke all on '+target+' from public,anon,authenticated,service_role,postgres');for(const entry of acl){const m=entry.match(/^([^=]*)=([^/]+)\/[^/]+$/);if(!m)throw Error('Unexpected ACL '+entry);const role=m[1]?quote(m[1]):'public';const permissions=[...m[2]].map(c=>privilege[c]);if(permissions.some(x=>!x))throw Error('Unsupported ACL '+entry);await db.exec('grant '+permissions.join(',')+' on '+target+' to '+role);}};
 for(const f of c.functions)await restoreAcl('function public.'+quote(f.name)+'('+f.args+')',f.acl);
 for(const r of c.relations){if(r.rls)await db.exec('alter table public.'+quote(r.name)+' enable row level security');if(r.force_rls)await db.exec('alter table public.'+quote(r.name)+' force row level security');await restoreAcl('table public.'+quote(r.name),r.acl);}
 for(const p of c.policies)await db.exec('create policy '+quote(p.policyname)+' on public.'+quote(p.tablename)+' as '+p.permissive+' for '+p.cmd+' to '+p.roles.map(x=>x==='public'?'public':quote(x)).join(',')+(p.qual?' using ('+p.qual+')':'')+(p.with_check?' with check ('+p.with_check+')':''));
 await db.exec('create schema cron;create table cron.job(jobid bigint,jobname text,schedule text,command text,active boolean,database text,username text);create schema supabase_migrations;create table supabase_migrations.schema_migrations(version text,name text);');
 for(const j of c.cron)await db.query('insert into cron.job values($1,$2,$3,$4,$5,$6,$7)',[j.jobid,j.jobname,j.schedule,j.command,j.active,j.database,j.username]);
 for(const m of c.migrations)await db.query('insert into supabase_migrations.schema_migrations values($1,$2)',[m.version,m.name]);
 await db.exec('set check_function_bodies=on;');
 const beforeFunctions=(await db.query("select proname,pg_get_function_identity_arguments(oid) args,md5(pg_get_functiondef(oid)) hash,proacl from pg_proc where pronamespace='public'::regnamespace and prokind='f' order by 1,2")).rows;
 result.steps.push({name:'catalog reconstruction',status:'PASS',tables:c.relations.length,functions:c.functions.filter(f=>f.definition).length});



 const release='docs/development/raid-production-release';
 const variants=JSON.parse(fs.readFileSync(release+'/variants-before.json'))[0].variants;
 await db.query('insert into canonical_raid_variants select * from jsonb_populate_recordset(null::canonical_raid_variants,$1::jsonb)',[JSON.stringify(variants)]);
 const apply=fs.readFileSync(release+'/bundle/apply-db.sql','utf8');
 const kpiBefore=(await db.query("select proname,md5(pg_get_functiondef(oid)) hash,proacl from pg_proc where proname in ('kpi_daily_engagement_v1','refresh_kpi_overview_saved_results') order by 1")).rows;
 await db.exec(apply.replace(/commit;\s*$/,'rollback;'));
 assert.equal((await db.query("select to_regclass('public.raid_rooms') value")).rows[0].value,null);
 result.steps.push({name:'Latest Production + KPI: exact DB bundle atomic rollback',status:'PASS'});
 await db.exec(apply);
 const kpiAfter=(await db.query("select proname,md5(pg_get_functiondef(oid)) hash,proacl from pg_proc where proname in ('kpi_daily_engagement_v1','refresh_kpi_overview_saved_results') order by 1")).rows;
 assert.deepEqual(kpiAfter,kpiBefore);
 assert.equal((await db.query('select count(*)::int n from raid_room_combat_profiles')).rows[0].n,28);
 result.steps.push({name:'Exact DB bundle COMMIT: 28 profiles, KPI bodies/ACL preserved',status:'PASS'});
 await db.exec('begin;'+fs.readFileSync(release+'/bundle/08-approved-settings.sql','utf8')+fs.readFileSync(release+'/bundle/09-open-operations.sql','utf8')+'commit;');
 result.settings=(await db.query("select jsonb_build_object('difficulty',(select jsonb_agg(to_jsonb(t) order by difficulty) from raid_room_difficulty_rules t),'clear',(select jsonb_agg(to_jsonb(t) order by difficulty) from raid_room_clear_reward_rules t),'clearItems',(select jsonb_agg(to_jsonb(t) order by difficulty) from raid_room_clear_reward_items t),'rescueItems',(select jsonb_agg(to_jsonb(t) order by difficulty) from raid_room_rescue_reward_items t)) rules")).rows[0].rules;
 const approved=JSON.parse(fs.readFileSync(release+'/approved-settings.json'));
 for(const p of approved.difficulties){const d=result.settings.difficulty.find(x=>x.difficulty===p.id),c=result.settings.clear.find(x=>x.difficulty===p.id);assert.equal(Number(d.rescue_min_battles),p.rescueMinimumBattles);assert.equal(Number(d.rescue_min_contribution_damage),p.rescueDamageInclusive);assert.equal(Number(c.minimum_contribution_damage),p.clearDamageExclusive);assert.equal(c.enabled,true);}
 result.steps.push({name:'Approved public settings and operation flag transaction',status:'PASS'});
 const stop=fs.readFileSync(release+'/bundle/05-stop-new-operations.sql','utf8');
 const stopBody=stop.slice(stop.indexOf('begin;'),stop.indexOf('\\if :raid_commit'));
 await db.exec(stopBody+'commit;');
 for(const t of ['raid_room_creation_settings','raid_room_battle_settings','raid_room_rescue_settings','raid_legacy_settings'])assert.equal((await db.query('select enabled from '+t)).rows[0].enabled,false);
 result.steps.push({name:'Prepared intake stop preserves data/schema',status:'PASS'});
 result.status='PASS';result.database=db.database;result.scope='Only current KPI drift, exact bundle, approved settings, atomic rollback and stop. Existing lifecycle/Edge/UI evidence reused.';
 fs.writeFileSync(release+'/rehearsal.json',JSON.stringify(result,null,2));console.log(JSON.stringify({status:result.status,database:db.database,steps:result.steps}));
}finally{await db.close();}
