import './safe-errors.mjs';
import {createRequire} from 'node:module';import {resolve} from 'node:path';const {chromium}=createRequire(resolve('../game03-tribe-neon-raid-preview-step5/package.json'))('@playwright/test');
import {roles,credentialsFor,save} from './qa-http.mjs';import fs from 'node:fs';
if(process.env.RAID_STEP6_DEPLOY_READY!=='true')throw Error('Parent deployment readiness required');
const target=process.env.RAID_STEP6_URL;const host=new URL(target).hostname;
if(!host.endsWith('.vercel.app')||!host.startsWith('tribe-neon-'))throw Error('Expected immutable project deployment URL');
const report=[];fs.mkdirSync('outputs/raid-step6/screens',{recursive:true});const browser=await chromium.launch();
try{for(const role of (process.env.RAID_STEP6_ROLES?process.env.RAID_STEP6_ROLES.split(','):roles)){const credential=credentialsFor(role);const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});const page=await context.newPage();const calls=[];page.on('response',response=>{const u=new URL(response.url());if(u.hostname==='sufvuqdnqohpfzkwxohq.supabase.co'&&u.pathname.startsWith('/rest/v1/rpc/'))calls.push({rpc:u.pathname.split('/').at(-1),status:response.status()});});
await page.goto(target);await page.getByRole('button',{name:'TAP TO START',exact:true}).click({timeout:30000});await page.getByRole('button',{name:'データをお持ちの方',exact:true}).click();await page.getByPlaceholder('メールアドレス',{exact:true}).fill(credential.email);await page.getByPlaceholder('パスワード (6文字以上)',{exact:true}).fill(credential.password);await page.getByRole('button',{name:'メールでログイン',exact:true}).click();await page.locator('.footer-mobile').waitFor({timeout:45000});
console.log(role+' UI login PASS');await page.reload();const tap=page.getByRole('button',{name:'TAP TO START',exact:true});await page.locator('.footer-mobile').or(tap).first().waitFor({timeout:30000});if(await tap.isVisible())await tap.click();const resume=page.getByRole('button',{name:'続きから',exact:true});await page.locator('.footer-mobile').or(resume).first().waitFor({timeout:30000});if(await resume.isVisible())await resume.click();await page.locator('.footer-mobile').waitFor({timeout:30000});await page.screenshot({path:`outputs/raid-step6/screens/${role}-home.png`});report.push({role,login:'PASS',reload:'PASS',calls});await context.close();}}
finally{await browser.close();save('browser-login',report);}console.log('PASS real UI login/reload for '+report.length+' existing QA roles');
