import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
const runtime = process.env.DB_TEST_RUNTIME_DIR;
const require = createRequire(runtime ? path.join(runtime, 'package.json') : import.meta.url);
const { PGlite } = require('@electric-sql/pglite');
const db = new PGlite();
const a = '11111111-1111-4111-8111-111111111111';
const b = '22222222-2222-4222-8222-222222222222';
await db.exec(`create role anon; create role authenticated;
create schema auth;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create table public.users(id uuid primary key, favorite_character_id text, current_base_id text);
create table public.user_characters(id int primary key, user_id uuid, character_id text);
create table public.formations(user_id uuid, character_ids text[]);
create table public.canonical_character_master(version text, character_id text, hometown text);
create function public.quest_town_key(text) returns text language sql immutable as $$ select $1 $$;
insert into users values('${a}','first','manual'),('${b}','other','other-town');
insert into user_characters values(1,'${a}','first'),(2,'${a}','leader'),(3,'${b}','other');
insert into formations values('${a}',array['first','leader']);
insert into canonical_character_master values('2026-08-21','leader','shibuya');`);
// Execute the actual production hometown trigger definition, not a replacement.
const triggerSource = readFileSync(new URL('../supabase/migrations/20260913062244_mission_receipt_projection_and_leader_town.sql', import.meta.url),'utf8');
await db.exec(triggerSource.slice(triggerSource.indexOf('create or replace function public.on_leader_hometown_base()')));
await db.exec(readFileSync(new URL('../supabase/migrations/20260914072613_profile_leader_authority_v1.sql', import.meta.url),'utf8'));
const call = (id) => db.query('select public.set_profile_leader_v1($1) result',[id]);
await assert.rejects(call('leader'), /authentication required/);
await db.query("select set_config('request.jwt.claim.sub',$1,false)",[a]);
await assert.rejects(call(null), /character id required/);
await assert.rejects(call('other'), /owned character not found/);
await assert.rejects(call('missing'), /owned character not found/);
await db.exec('set role authenticated');
const result = await call('leader');
assert.deepEqual(result.rows[0].result,{status:'success',favorite_character_id:'leader'});
await db.exec('reset role');
assert.deepEqual((await db.query('select favorite_character_id,current_base_id from users where id=$1',[a])).rows[0],{favorite_character_id:'leader',current_base_id:'shibuya'});
await db.query("update users set current_base_id='yokohama' where id=$1",[a]);
await call('leader');
assert.equal((await db.query('select current_base_id from users where id=$1',[a])).rows[0].current_base_id,'yokohama');
assert.deepEqual((await db.query('select character_ids from formations where user_id=$1',[a])).rows[0].character_ids,['first','leader']);
assert.equal((await db.query('select favorite_character_id from users where id=$1',[b])).rows[0].favorite_character_id,'other');
assert.equal((await db.query("select has_function_privilege('anon','public.set_profile_leader_v1(text)','EXECUTE') allowed")).rows[0].allowed,false);
assert.equal((await db.query("select has_function_privilege('authenticated','public.set_profile_leader_v1(text)','EXECUTE') allowed")).rows[0].allowed,true);
await db.query("select set_config('request.jwt.claim.sub','33333333-3333-4333-8333-333333333333',false)");
await assert.rejects(call('leader'),/profile not found/);
await db.close();
console.log('PASS: auth, ownership, input, profile, caller grants, non-head Leader, unchanged formation/other user, hometown trigger, repeat/manual base');
