import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
const require=createRequire(process.env.DB_TEST_RUNTIME_DIR?path.join(process.env.DB_TEST_RUNTIME_DIR,'package.json'):import.meta.url);
const {PGlite}=require('@electric-sql/pglite'); const db=new PGlite();
const uid='11111111-1111-4111-8111-111111111111'; const pid='22222222-2222-4222-8222-222222222222';
await db.exec(`create role anon;create role authenticated;create schema auth;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table user_patrols(id uuid,user_id uuid,status text,expires_at timestamptz,has_battle_event boolean,battle_resolved boolean,encounter_snapshot jsonb,character_id text);
create table user_main_formations(user_id uuid,slot int,user_character_id uuid);
create table user_characters(id uuid,user_id uuid,character_id text,level int,awakening_level int);
create table user_power_rankings(user_id uuid,total_power bigint);
create function calculate_user_character_power(uuid,uuid) returns bigint language sql as $$ select 100::bigint $$;
create table battle_replay_sessions(id uuid default gen_random_uuid(),requester_user_id uuid,battle_mode text,source_reference_id uuid,tactic_id text,enemy_tactic_id text,random_seed bigint,player_snapshot jsonb,enemy_snapshot jsonb,resolution_authority text);
-- Snapshot builder test double records exactly what the real orchestration passes.
create function build_server_battle_snapshot(uuid,text[],text) returns jsonb language sql as $$select to_jsonb($2)$$;
insert into user_patrols values('${pid}','${uid}','CLAIMABLE',now(),true,false,'{"members":[{"id":"enemy"}],"enemyTactic":"BALANCED"}','explorer');
insert into user_characters select ('00000000-0000-4000-8000-'||lpad(i::text,12,'0'))::uuid,'${uid}','char'||i,1,0 from generate_series(1,5)i;
insert into user_main_formations select '${uid}',row_number()over()::int,id from user_characters order by character_id desc;`);
const source=readFileSync(new URL('../supabase/migrations/20260817000154_ranking_power_p0_foundation.sql',import.meta.url),'utf8');
const start=source.indexOf('create or replace function public.get_current_main_formation()');await db.exec(source.slice(start,source.indexOf('$$;',source.indexOf('as $$',start))+3));
await db.exec(readFileSync(new URL('../supabase/migrations/20260914075032_quest_main_formation_authority.sql',import.meta.url),'utf8'));
const call=()=>db.query('select create_patrol_battle_replay($1) result',[pid]);
await assert.rejects(call(),/authentication required/);
await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);
const expected=(await db.query('select get_current_main_formation() f')).rows[0].f.characters.map(c=>c.character_id);
await db.exec('set role authenticated');let r=(await call()).rows[0].result;await db.exec('reset role');
assert.deepEqual(r.player_snapshot,expected);assert.equal(r.player_snapshot.length,5);assert.ok(!r.player_snapshot.includes('explorer'));
await db.exec('update user_main_formations set slot=6-slot');
r=(await call()).rows[0].result;assert.deepEqual(r.player_snapshot,[...expected].reverse());
assert.equal((await db.query('select character_id from user_patrols')).rows[0].character_id,'explorer');
await db.exec('delete from user_main_formations');await assert.rejects(call(),/saved main formation required/);
assert.equal((await db.query('select count(*)::int n from battle_replay_sessions')).rows[0].n,2);
await db.exec("update user_patrols set status='ONGOING',expires_at=now()-interval '1 second'");
await assert.rejects(call(),/saved main formation required/);assert.equal((await db.query('select status from user_patrols')).rows[0].status,'ONGOING');
const tutorial=readFileSync(new URL('../supabase/migrations/20260823000192_tutorial_canonical_growth_before_formation.sql',import.meta.url),'utf8');
assert.match(tutorial,/public\.save_main_formation\(v_party\)/);
assert.match(readFileSync(new URL('../src/hooks/useBattle.ts',import.meta.url),'utf8'),/mode === "PATROL" \|\| mode === "PVP" \|\| mode === "RAID"/);
await db.close();console.log('PASS: actual Quest/get-main RPC, 5-member saved order, new battle reflects changed order, explorer excluded/unchanged, no fallback, auth, atomic rejection; tutorial saved-main source contract');
