import assert from 'node:assert/strict';
import { monthlyRows } from '../src/utils/kpiMonthly.ts';
const metric = (n, d) => ({ numerator:n, denominator:d, value:d ? n/d : null, target:.6, status:d ? 'PASS' : 'NOT_READY', authority:'tutorial_completion_union_v1' });
const row = (date, n, d, mature=true) => ({ date, new_users:d, tutorial:metric(n,d), guild:metric(n,n), chat:metric(0,n), retention:[1,2,3,4,5].map(day=>({day,...(mature?metric(n,d):{...metric(null,null),observation_status:'incomplete'})})) });
const rows=[row('2026-09-01',1,2),row('2026-09-02',9,90),row('2026-09-08',4,5,false),row('2026-08-31',1,3)];
const [month,previous]=monthlyRows(rows,'2026-09-08');
assert.equal(month.date,'2026-09'); assert.equal(month.new_users,97);
assert.equal(month.tutorial.numerator,14); assert.equal(month.tutorial.denominator,97); assert.equal(month.tutorial.value,14/97);
assert.equal(month.retention[0].value,10/92); assert.equal(month.retention[0].denominator,92);
assert.equal(month.retention[0].reason,'mature_cohorts_only'); assert.equal(month.partial,true);
assert.equal(previous.partial,false); assert.equal(previous.tutorial.denominator,3);
const empty=monthlyRows([row('2024-02-29',0,0)],'2024-03-01')[0];
assert.equal(empty.tutorial.numerator,0); assert.equal(empty.tutorial.denominator,0); assert.equal(empty.tutorial.value,null);
assert.equal(empty.retention[0].value,null); assert.equal(empty.date,'2024-02');
assert.deepEqual(monthlyRows([],'2026-09-08'),[]);
const unavailable=row('2026-09-03',0,10); unavailable.chat={...metric(null,null),status:'UNAVAILABLE'};
assert.equal(monthlyRows([...rows,unavailable],'2026-09-08')[0].chat.status,'UNAVAILABLE');
assert.equal(monthlyRows([row('2026-09-08',1,2,false)],'2026-09-08')[0].retention[0].value,null);
console.log('PASS monthly weighted counts, individual maturity, missing vs zero, empty, month boundary, leap day, source failure');
