import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import assert from 'node:assert/strict';
const source=fs.readFileSync('src/domain/quest/raidEncounter.ts','utf8');
const exports={};vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports});
const {parseQuestRaidEncounter:parse,isEncounterPresentationSafe:safe}=exports;
assert.throws(()=>parse({status:'CREATED',patrolId:'p'}));
const result=parse({status:'CREATED',patrolId:'p',roomId:'r',areaId:'shibuya',difficulty:'advanced',bossName:'boss',bonusItems:[{itemId:'x',quantity:2}]});
assert.equal(result.difficulty,'advanced');assert.equal(result.roomId,'r');
assert.throws(()=>parse({...result,bonusItems:[{itemId:'x',quantity:-1}]}));
assert.throws(()=>parse({...result,difficulty:'expert'}));
const base={battle:null,gacha:null,dialog:null,mission:false,patrolReward:false,blocked:false};
assert.equal(safe(base),true);
for(const key of Object.keys(base))assert.equal(safe({...base,[key]:true}),false,key);
console.log('PASS: Encounter protocol and Battle/Gacha/Result/Mission interaction exclusion');
