-- Restore the existing InboxPanel news contract. No release is published here.
-- Deliberately fail if an unexpected news table already exists: reconcile first.
BEGIN;
CREATE TABLE public.news (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL CHECK (category IN ('IMPORTANT', 'EVENT', 'INFO')),
  title text NOT NULL,
  content text NOT NULL,
  link_url text,
  start_at timestamptz NOT NULL,
  end_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  is_published boolean NOT NULL DEFAULT false,
  release_key text UNIQUE,
  CHECK (end_at IS NULL OR end_at > start_at)
);
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.news FROM anon, authenticated;
GRANT SELECT ON public.news TO anon, authenticated;
GRANT ALL ON public.news TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.news_id_seq TO service_role;
CREATE POLICY news_read_published ON public.news FOR SELECT TO anon, authenticated
  USING (is_published AND start_at <= now() AND (end_at IS NULL OR end_at > now()));
COMMIT;
